// Code generated by go-swagger; DO NOT EDIT.

package container

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetV1WorkloadIDConfigParams creates a new GetV1WorkloadIDConfigParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetV1WorkloadIDConfigParams() *GetV1WorkloadIDConfigParams {
	return &GetV1WorkloadIDConfigParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1WorkloadIDConfigParamsWithTimeout creates a new GetV1WorkloadIDConfigParams object
// with the ability to set a timeout on a request.
func NewGetV1WorkloadIDConfigParamsWithTimeout(timeout time.Duration) *GetV1WorkloadIDConfigParams {
	return &GetV1WorkloadIDConfigParams{
		timeout: timeout,
	}
}

// NewGetV1WorkloadIDConfigParamsWithContext creates a new GetV1WorkloadIDConfigParams object
// with the ability to set a context for a request.
func NewGetV1WorkloadIDConfigParamsWithContext(ctx context.Context) *GetV1WorkloadIDConfigParams {
	return &GetV1WorkloadIDConfigParams{
		Context: ctx,
	}
}

// NewGetV1WorkloadIDConfigParamsWithHTTPClient creates a new GetV1WorkloadIDConfigParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetV1WorkloadIDConfigParamsWithHTTPClient(client *http.Client) *GetV1WorkloadIDConfigParams {
	return &GetV1WorkloadIDConfigParams{
		HTTPClient: client,
	}
}

/*
GetV1WorkloadIDConfigParams contains all the parameters to send to the API endpoint

	for the get v1 workload ID config operation.

	Typically these are written to a http.Request.
*/
type GetV1WorkloadIDConfigParams struct {

	// XAuthToken.
	XAuthToken string

	/* ID.

	   container ID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get v1 workload ID config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1WorkloadIDConfigParams) WithDefaults() *GetV1WorkloadIDConfigParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get v1 workload ID config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1WorkloadIDConfigParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get v1 workload ID config params
func (o *GetV1WorkloadIDConfigParams) WithTimeout(timeout time.Duration) *GetV1WorkloadIDConfigParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1 workload ID config params
func (o *GetV1WorkloadIDConfigParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1 workload ID config params
func (o *GetV1WorkloadIDConfigParams) WithContext(ctx context.Context) *GetV1WorkloadIDConfigParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1 workload ID config params
func (o *GetV1WorkloadIDConfigParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1 workload ID config params
func (o *GetV1WorkloadIDConfigParams) WithHTTPClient(client *http.Client) *GetV1WorkloadIDConfigParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1 workload ID config params
func (o *GetV1WorkloadIDConfigParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAuthToken adds the xAuthToken to the get v1 workload ID config params
func (o *GetV1WorkloadIDConfigParams) WithXAuthToken(xAuthToken string) *GetV1WorkloadIDConfigParams {
	o.SetXAuthToken(xAuthToken)
	return o
}

// SetXAuthToken adds the xAuthToken to the get v1 workload ID config params
func (o *GetV1WorkloadIDConfigParams) SetXAuthToken(xAuthToken string) {
	o.XAuthToken = xAuthToken
}

// WithID adds the id to the get v1 workload ID config params
func (o *GetV1WorkloadIDConfigParams) WithID(id string) *GetV1WorkloadIDConfigParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get v1 workload ID config params
func (o *GetV1WorkloadIDConfigParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1WorkloadIDConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Auth-Token
	if err := r.SetHeaderParam("X-Auth-Token", o.XAuthToken); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
