// Code generated by go-swagger; DO NOT EDIT.

package server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteV1ServerNameReader is a Reader for the DeleteV1ServerName structure.
type DeleteV1ServerNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteV1ServerNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteV1ServerNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /v1/server/{name}] DeleteV1ServerName", response, response.Code())
	}
}

// NewDeleteV1ServerNameOK creates a DeleteV1ServerNameOK with default headers values
func NewDeleteV1ServerNameOK() *DeleteV1ServerNameOK {
	return &DeleteV1ServerNameOK{}
}

/*
DeleteV1ServerNameOK describes a response with status code 200, with default header values.

Success
*/
type DeleteV1ServerNameOK struct {
}

// IsSuccess returns true when this delete v1 server name o k response has a 2xx status code
func (o *DeleteV1ServerNameOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete v1 server name o k response has a 3xx status code
func (o *DeleteV1ServerNameOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete v1 server name o k response has a 4xx status code
func (o *DeleteV1ServerNameOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete v1 server name o k response has a 5xx status code
func (o *DeleteV1ServerNameOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete v1 server name o k response a status code equal to that given
func (o *DeleteV1ServerNameOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete v1 server name o k response
func (o *DeleteV1ServerNameOK) Code() int {
	return 200
}

func (o *DeleteV1ServerNameOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/server/{name}][%d] deleteV1ServerNameOK ", 200)
}

func (o *DeleteV1ServerNameOK) String() string {
	return fmt.Sprintf("[DELETE /v1/server/{name}][%d] deleteV1ServerNameOK ", 200)
}

func (o *DeleteV1ServerNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
