// Code generated by go-swagger; DO NOT EDIT.

package server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PatchV1ServerNameReader is a Reader for the PatchV1ServerName structure.
type PatchV1ServerNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchV1ServerNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPatchV1ServerNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PATCH /v1/server/{name}] PatchV1ServerName", response, response.Code())
	}
}

// NewPatchV1ServerNameOK creates a PatchV1ServerNameOK with default headers values
func NewPatchV1ServerNameOK() *PatchV1ServerNameOK {
	return &PatchV1ServerNameOK{}
}

/*
PatchV1ServerNameOK describes a response with status code 200, with default header values.

Success
*/
type PatchV1ServerNameOK struct {
}

// IsSuccess returns true when this patch v1 server name o k response has a 2xx status code
func (o *PatchV1ServerNameOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this patch v1 server name o k response has a 3xx status code
func (o *PatchV1ServerNameOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this patch v1 server name o k response has a 4xx status code
func (o *PatchV1ServerNameOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this patch v1 server name o k response has a 5xx status code
func (o *PatchV1ServerNameOK) IsServerError() bool {
	return false
}

// IsCode returns true when this patch v1 server name o k response a status code equal to that given
func (o *PatchV1ServerNameOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the patch v1 server name o k response
func (o *PatchV1ServerNameOK) Code() int {
	return 200
}

func (o *PatchV1ServerNameOK) Error() string {
	return fmt.Sprintf("[PATCH /v1/server/{name}][%d] patchV1ServerNameOK ", 200)
}

func (o *PatchV1ServerNameOK) String() string {
	return fmt.Sprintf("[PATCH /v1/server/{name}][%d] patchV1ServerNameOK ", 200)
}

func (o *PatchV1ServerNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
