// Code generated by go-swagger; DO NOT EDIT.

package log

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetV1LogThreatIDParams creates a new GetV1LogThreatIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetV1LogThreatIDParams() *GetV1LogThreatIDParams {
	return &GetV1LogThreatIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1LogThreatIDParamsWithTimeout creates a new GetV1LogThreatIDParams object
// with the ability to set a timeout on a request.
func NewGetV1LogThreatIDParamsWithTimeout(timeout time.Duration) *GetV1LogThreatIDParams {
	return &GetV1LogThreatIDParams{
		timeout: timeout,
	}
}

// NewGetV1LogThreatIDParamsWithContext creates a new GetV1LogThreatIDParams object
// with the ability to set a context for a request.
func NewGetV1LogThreatIDParamsWithContext(ctx context.Context) *GetV1LogThreatIDParams {
	return &GetV1LogThreatIDParams{
		Context: ctx,
	}
}

// NewGetV1LogThreatIDParamsWithHTTPClient creates a new GetV1LogThreatIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetV1LogThreatIDParamsWithHTTPClient(client *http.Client) *GetV1LogThreatIDParams {
	return &GetV1LogThreatIDParams{
		HTTPClient: client,
	}
}

/*
GetV1LogThreatIDParams contains all the parameters to send to the API endpoint

	for the get v1 log threat ID operation.

	Typically these are written to a http.Request.
*/
type GetV1LogThreatIDParams struct {

	/* ID.

	   Threat ID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get v1 log threat ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1LogThreatIDParams) WithDefaults() *GetV1LogThreatIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get v1 log threat ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1LogThreatIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get v1 log threat ID params
func (o *GetV1LogThreatIDParams) WithTimeout(timeout time.Duration) *GetV1LogThreatIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1 log threat ID params
func (o *GetV1LogThreatIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1 log threat ID params
func (o *GetV1LogThreatIDParams) WithContext(ctx context.Context) *GetV1LogThreatIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1 log threat ID params
func (o *GetV1LogThreatIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1 log threat ID params
func (o *GetV1LogThreatIDParams) WithHTTPClient(client *http.Client) *GetV1LogThreatIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1 log threat ID params
func (o *GetV1LogThreatIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get v1 log threat ID params
func (o *GetV1LogThreatIDParams) WithID(id string) *GetV1LogThreatIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get v1 log threat ID params
func (o *GetV1LogThreatIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1LogThreatIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
