// Code generated by go-swagger; DO NOT EDIT.

package w_a_f_rule

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PatchV1WafGroupNameReader is a Reader for the PatchV1WafGroupName structure.
type PatchV1WafGroupNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchV1WafGroupNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPatchV1WafGroupNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PATCH /v1/waf/group/{name}] PatchV1WafGroupName", response, response.Code())
	}
}

// NewPatchV1WafGroupNameOK creates a PatchV1WafGroupNameOK with default headers values
func NewPatchV1WafGroupNameOK() *PatchV1WafGroupNameOK {
	return &PatchV1WafGroupNameOK{}
}

/*
PatchV1WafGroupNameOK describes a response with status code 200, with default header values.

Success
*/
type PatchV1WafGroupNameOK struct {
}

// IsSuccess returns true when this patch v1 waf group name o k response has a 2xx status code
func (o *PatchV1WafGroupNameOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this patch v1 waf group name o k response has a 3xx status code
func (o *PatchV1WafGroupNameOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this patch v1 waf group name o k response has a 4xx status code
func (o *PatchV1WafGroupNameOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this patch v1 waf group name o k response has a 5xx status code
func (o *PatchV1WafGroupNameOK) IsServerError() bool {
	return false
}

// IsCode returns true when this patch v1 waf group name o k response a status code equal to that given
func (o *PatchV1WafGroupNameOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the patch v1 waf group name o k response
func (o *PatchV1WafGroupNameOK) Code() int {
	return 200
}

func (o *PatchV1WafGroupNameOK) Error() string {
	return fmt.Sprintf("[PATCH /v1/waf/group/{name}][%d] patchV1WafGroupNameOK ", 200)
}

func (o *PatchV1WafGroupNameOK) String() string {
	return fmt.Sprintf("[PATCH /v1/waf/group/{name}][%d] patchV1WafGroupNameOK ", 200)
}

func (o *PatchV1WafGroupNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
