// Code generated by go-swagger; DO NOT EDIT.

package w_a_f_rule

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PatchV1WafSersorNameReader is a Reader for the PatchV1WafSersorName structure.
type PatchV1WafSersorNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchV1WafSersorNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPatchV1WafSersorNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PATCH /v1/waf/sersor/{name}] PatchV1WafSersorName", response, response.Code())
	}
}

// NewPatchV1WafSersorNameOK creates a PatchV1WafSersorNameOK with default headers values
func NewPatchV1WafSersorNameOK() *PatchV1WafSersorNameOK {
	return &PatchV1WafSersorNameOK{}
}

/*
PatchV1WafSersorNameOK describes a response with status code 200, with default header values.

Success
*/
type PatchV1WafSersorNameOK struct {
}

// IsSuccess returns true when this patch v1 waf sersor name o k response has a 2xx status code
func (o *PatchV1WafSersorNameOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this patch v1 waf sersor name o k response has a 3xx status code
func (o *PatchV1WafSersorNameOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this patch v1 waf sersor name o k response has a 4xx status code
func (o *PatchV1WafSersorNameOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this patch v1 waf sersor name o k response has a 5xx status code
func (o *PatchV1WafSersorNameOK) IsServerError() bool {
	return false
}

// IsCode returns true when this patch v1 waf sersor name o k response a status code equal to that given
func (o *PatchV1WafSersorNameOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the patch v1 waf sersor name o k response
func (o *PatchV1WafSersorNameOK) Code() int {
	return 200
}

func (o *PatchV1WafSersorNameOK) Error() string {
	return fmt.Sprintf("[PATCH /v1/waf/sersor/{name}][%d] patchV1WafSersorNameOK ", 200)
}

func (o *PatchV1WafSersorNameOK) String() string {
	return fmt.Sprintf("[PATCH /v1/waf/sersor/{name}][%d] patchV1WafSersorNameOK ", 200)
}

func (o *PatchV1WafSersorNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
