// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetV1ServiceParams creates a new GetV1ServiceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetV1ServiceParams() *GetV1ServiceParams {
	return &GetV1ServiceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1ServiceParamsWithTimeout creates a new GetV1ServiceParams object
// with the ability to set a timeout on a request.
func NewGetV1ServiceParamsWithTimeout(timeout time.Duration) *GetV1ServiceParams {
	return &GetV1ServiceParams{
		timeout: timeout,
	}
}

// NewGetV1ServiceParamsWithContext creates a new GetV1ServiceParams object
// with the ability to set a context for a request.
func NewGetV1ServiceParamsWithContext(ctx context.Context) *GetV1ServiceParams {
	return &GetV1ServiceParams{
		Context: ctx,
	}
}

// NewGetV1ServiceParamsWithHTTPClient creates a new GetV1ServiceParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetV1ServiceParamsWithHTTPClient(client *http.Client) *GetV1ServiceParams {
	return &GetV1ServiceParams{
		HTTPClient: client,
	}
}

/*
GetV1ServiceParams contains all the parameters to send to the API endpoint

	for the get v1 service operation.

	Typically these are written to a http.Request.
*/
type GetV1ServiceParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get v1 service params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1ServiceParams) WithDefaults() *GetV1ServiceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get v1 service params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1ServiceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get v1 service params
func (o *GetV1ServiceParams) WithTimeout(timeout time.Duration) *GetV1ServiceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1 service params
func (o *GetV1ServiceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1 service params
func (o *GetV1ServiceParams) WithContext(ctx context.Context) *GetV1ServiceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1 service params
func (o *GetV1ServiceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1 service params
func (o *GetV1ServiceParams) WithHTTPClient(client *http.Client) *GetV1ServiceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1 service params
func (o *GetV1ServiceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1ServiceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
