// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/minchao/neuvector-sdk/models"
)

// NewPatchV1ServiceConfigParams creates a new PatchV1ServiceConfigParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPatchV1ServiceConfigParams() *PatchV1ServiceConfigParams {
	return &PatchV1ServiceConfigParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPatchV1ServiceConfigParamsWithTimeout creates a new PatchV1ServiceConfigParams object
// with the ability to set a timeout on a request.
func NewPatchV1ServiceConfigParamsWithTimeout(timeout time.Duration) *PatchV1ServiceConfigParams {
	return &PatchV1ServiceConfigParams{
		timeout: timeout,
	}
}

// NewPatchV1ServiceConfigParamsWithContext creates a new PatchV1ServiceConfigParams object
// with the ability to set a context for a request.
func NewPatchV1ServiceConfigParamsWithContext(ctx context.Context) *PatchV1ServiceConfigParams {
	return &PatchV1ServiceConfigParams{
		Context: ctx,
	}
}

// NewPatchV1ServiceConfigParamsWithHTTPClient creates a new PatchV1ServiceConfigParams object
// with the ability to set a custom HTTPClient for a request.
func NewPatchV1ServiceConfigParamsWithHTTPClient(client *http.Client) *PatchV1ServiceConfigParams {
	return &PatchV1ServiceConfigParams{
		HTTPClient: client,
	}
}

/*
PatchV1ServiceConfigParams contains all the parameters to send to the API endpoint

	for the patch v1 service config operation.

	Typically these are written to a http.Request.
*/
type PatchV1ServiceConfigParams struct {

	// XAuthToken.
	XAuthToken string

	/* Body.

	   Service configure data
	*/
	Body *models.RESTServiceBatchConfigData

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the patch v1 service config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchV1ServiceConfigParams) WithDefaults() *PatchV1ServiceConfigParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the patch v1 service config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchV1ServiceConfigParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the patch v1 service config params
func (o *PatchV1ServiceConfigParams) WithTimeout(timeout time.Duration) *PatchV1ServiceConfigParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch v1 service config params
func (o *PatchV1ServiceConfigParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch v1 service config params
func (o *PatchV1ServiceConfigParams) WithContext(ctx context.Context) *PatchV1ServiceConfigParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch v1 service config params
func (o *PatchV1ServiceConfigParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch v1 service config params
func (o *PatchV1ServiceConfigParams) WithHTTPClient(client *http.Client) *PatchV1ServiceConfigParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch v1 service config params
func (o *PatchV1ServiceConfigParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAuthToken adds the xAuthToken to the patch v1 service config params
func (o *PatchV1ServiceConfigParams) WithXAuthToken(xAuthToken string) *PatchV1ServiceConfigParams {
	o.SetXAuthToken(xAuthToken)
	return o
}

// SetXAuthToken adds the xAuthToken to the patch v1 service config params
func (o *PatchV1ServiceConfigParams) SetXAuthToken(xAuthToken string) {
	o.XAuthToken = xAuthToken
}

// WithBody adds the body to the patch v1 service config params
func (o *PatchV1ServiceConfigParams) WithBody(body *models.RESTServiceBatchConfigData) *PatchV1ServiceConfigParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the patch v1 service config params
func (o *PatchV1ServiceConfigParams) SetBody(body *models.RESTServiceBatchConfigData) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PatchV1ServiceConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Auth-Token
	if err := r.SetHeaderParam("X-Auth-Token", o.XAuthToken); err != nil {
		return err
	}
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
