// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PatchV1ServiceConfigReader is a Reader for the PatchV1ServiceConfig structure.
type PatchV1ServiceConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchV1ServiceConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPatchV1ServiceConfigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PATCH /v1/service/config] PatchV1ServiceConfig", response, response.Code())
	}
}

// NewPatchV1ServiceConfigOK creates a PatchV1ServiceConfigOK with default headers values
func NewPatchV1ServiceConfigOK() *PatchV1ServiceConfigOK {
	return &PatchV1ServiceConfigOK{}
}

/*
PatchV1ServiceConfigOK describes a response with status code 200, with default header values.

Success
*/
type PatchV1ServiceConfigOK struct {
}

// IsSuccess returns true when this patch v1 service config o k response has a 2xx status code
func (o *PatchV1ServiceConfigOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this patch v1 service config o k response has a 3xx status code
func (o *PatchV1ServiceConfigOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this patch v1 service config o k response has a 4xx status code
func (o *PatchV1ServiceConfigOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this patch v1 service config o k response has a 5xx status code
func (o *PatchV1ServiceConfigOK) IsServerError() bool {
	return false
}

// IsCode returns true when this patch v1 service config o k response a status code equal to that given
func (o *PatchV1ServiceConfigOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the patch v1 service config o k response
func (o *PatchV1ServiceConfigOK) Code() int {
	return 200
}

func (o *PatchV1ServiceConfigOK) Error() string {
	return fmt.Sprintf("[PATCH /v1/service/config][%d] patchV1ServiceConfigOK ", 200)
}

func (o *PatchV1ServiceConfigOK) String() string {
	return fmt.Sprintf("[PATCH /v1/service/config][%d] patchV1ServiceConfigOK ", 200)
}

func (o *PatchV1ServiceConfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
