// Code generated by go-swagger; DO NOT EDIT.

package policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostV1PolicyRulesPromoteReader is a Reader for the PostV1PolicyRulesPromote structure.
type PostV1PolicyRulesPromoteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostV1PolicyRulesPromoteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostV1PolicyRulesPromoteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /v1/policy/rules/promote] PostV1PolicyRulesPromote", response, response.Code())
	}
}

// NewPostV1PolicyRulesPromoteOK creates a PostV1PolicyRulesPromoteOK with default headers values
func NewPostV1PolicyRulesPromoteOK() *PostV1PolicyRulesPromoteOK {
	return &PostV1PolicyRulesPromoteOK{}
}

/*
PostV1PolicyRulesPromoteOK describes a response with status code 200, with default header values.

Success
*/
type PostV1PolicyRulesPromoteOK struct {
}

// IsSuccess returns true when this post v1 policy rules promote o k response has a 2xx status code
func (o *PostV1PolicyRulesPromoteOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post v1 policy rules promote o k response has a 3xx status code
func (o *PostV1PolicyRulesPromoteOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post v1 policy rules promote o k response has a 4xx status code
func (o *PostV1PolicyRulesPromoteOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post v1 policy rules promote o k response has a 5xx status code
func (o *PostV1PolicyRulesPromoteOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post v1 policy rules promote o k response a status code equal to that given
func (o *PostV1PolicyRulesPromoteOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post v1 policy rules promote o k response
func (o *PostV1PolicyRulesPromoteOK) Code() int {
	return 200
}

func (o *PostV1PolicyRulesPromoteOK) Error() string {
	return fmt.Sprintf("[POST /v1/policy/rules/promote][%d] postV1PolicyRulesPromoteOK ", 200)
}

func (o *PostV1PolicyRulesPromoteOK) String() string {
	return fmt.Sprintf("[POST /v1/policy/rules/promote][%d] postV1PolicyRulesPromoteOK ", 200)
}

func (o *PostV1PolicyRulesPromoteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
