// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteV1UserRoleNameReader is a Reader for the DeleteV1UserRoleName structure.
type DeleteV1UserRoleNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteV1UserRoleNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteV1UserRoleNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /v1/user_role/{name}] DeleteV1UserRoleName", response, response.Code())
	}
}

// NewDeleteV1UserRoleNameOK creates a DeleteV1UserRoleNameOK with default headers values
func NewDeleteV1UserRoleNameOK() *DeleteV1UserRoleNameOK {
	return &DeleteV1UserRoleNameOK{}
}

/*
DeleteV1UserRoleNameOK describes a response with status code 200, with default header values.

Success
*/
type DeleteV1UserRoleNameOK struct {
}

// IsSuccess returns true when this delete v1 user role name o k response has a 2xx status code
func (o *DeleteV1UserRoleNameOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete v1 user role name o k response has a 3xx status code
func (o *DeleteV1UserRoleNameOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete v1 user role name o k response has a 4xx status code
func (o *DeleteV1UserRoleNameOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete v1 user role name o k response has a 5xx status code
func (o *DeleteV1UserRoleNameOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete v1 user role name o k response a status code equal to that given
func (o *DeleteV1UserRoleNameOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete v1 user role name o k response
func (o *DeleteV1UserRoleNameOK) Code() int {
	return 200
}

func (o *DeleteV1UserRoleNameOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/user_role/{name}][%d] deleteV1UserRoleNameOK ", 200)
}

func (o *DeleteV1UserRoleNameOK) String() string {
	return fmt.Sprintf("[DELETE /v1/user_role/{name}][%d] deleteV1UserRoleNameOK ", 200)
}

func (o *DeleteV1UserRoleNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
