// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteV1UserFullnameReader is a Reader for the DeleteV1UserFullname structure.
type DeleteV1UserFullnameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteV1UserFullnameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteV1UserFullnameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /v1/user/{fullname}] DeleteV1UserFullname", response, response.Code())
	}
}

// NewDeleteV1UserFullnameOK creates a DeleteV1UserFullnameOK with default headers values
func NewDeleteV1UserFullnameOK() *DeleteV1UserFullnameOK {
	return &DeleteV1UserFullnameOK{}
}

/*
DeleteV1UserFullnameOK describes a response with status code 200, with default header values.

Success
*/
type DeleteV1UserFullnameOK struct {
}

// IsSuccess returns true when this delete v1 user fullname o k response has a 2xx status code
func (o *DeleteV1UserFullnameOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete v1 user fullname o k response has a 3xx status code
func (o *DeleteV1UserFullnameOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete v1 user fullname o k response has a 4xx status code
func (o *DeleteV1UserFullnameOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete v1 user fullname o k response has a 5xx status code
func (o *DeleteV1UserFullnameOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete v1 user fullname o k response a status code equal to that given
func (o *DeleteV1UserFullnameOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete v1 user fullname o k response
func (o *DeleteV1UserFullnameOK) Code() int {
	return 200
}

func (o *DeleteV1UserFullnameOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/user/{fullname}][%d] deleteV1UserFullnameOK ", 200)
}

func (o *DeleteV1UserFullnameOK) String() string {
	return fmt.Sprintf("[DELETE /v1/user/{fullname}][%d] deleteV1UserFullnameOK ", 200)
}

func (o *DeleteV1UserFullnameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
