// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/minchao/neuvector-sdk/models"
)

// GetV1PasswordProfileReader is a Reader for the GetV1PasswordProfile structure.
type GetV1PasswordProfileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetV1PasswordProfileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetV1PasswordProfileOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /v1/password_profile] GetV1PasswordProfile", response, response.Code())
	}
}

// NewGetV1PasswordProfileOK creates a GetV1PasswordProfileOK with default headers values
func NewGetV1PasswordProfileOK() *GetV1PasswordProfileOK {
	return &GetV1PasswordProfileOK{}
}

/*
GetV1PasswordProfileOK describes a response with status code 200, with default header values.

Success
*/
type GetV1PasswordProfileOK struct {
	Payload *models.RESTPwdProfilesData
}

// IsSuccess returns true when this get v1 password profile o k response has a 2xx status code
func (o *GetV1PasswordProfileOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get v1 password profile o k response has a 3xx status code
func (o *GetV1PasswordProfileOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 password profile o k response has a 4xx status code
func (o *GetV1PasswordProfileOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get v1 password profile o k response has a 5xx status code
func (o *GetV1PasswordProfileOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get v1 password profile o k response a status code equal to that given
func (o *GetV1PasswordProfileOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get v1 password profile o k response
func (o *GetV1PasswordProfileOK) Code() int {
	return 200
}

func (o *GetV1PasswordProfileOK) Error() string {
	return fmt.Sprintf("[GET /v1/password_profile][%d] getV1PasswordProfileOK  %+v", 200, o.Payload)
}

func (o *GetV1PasswordProfileOK) String() string {
	return fmt.Sprintf("[GET /v1/password_profile][%d] getV1PasswordProfileOK  %+v", 200, o.Payload)
}

func (o *GetV1PasswordProfileOK) GetPayload() *models.RESTPwdProfilesData {
	return o.Payload
}

func (o *GetV1PasswordProfileOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RESTPwdProfilesData)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
