// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetV1UserRoleParams creates a new GetV1UserRoleParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetV1UserRoleParams() *GetV1UserRoleParams {
	return &GetV1UserRoleParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1UserRoleParamsWithTimeout creates a new GetV1UserRoleParams object
// with the ability to set a timeout on a request.
func NewGetV1UserRoleParamsWithTimeout(timeout time.Duration) *GetV1UserRoleParams {
	return &GetV1UserRoleParams{
		timeout: timeout,
	}
}

// NewGetV1UserRoleParamsWithContext creates a new GetV1UserRoleParams object
// with the ability to set a context for a request.
func NewGetV1UserRoleParamsWithContext(ctx context.Context) *GetV1UserRoleParams {
	return &GetV1UserRoleParams{
		Context: ctx,
	}
}

// NewGetV1UserRoleParamsWithHTTPClient creates a new GetV1UserRoleParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetV1UserRoleParamsWithHTTPClient(client *http.Client) *GetV1UserRoleParams {
	return &GetV1UserRoleParams{
		HTTPClient: client,
	}
}

/*
GetV1UserRoleParams contains all the parameters to send to the API endpoint

	for the get v1 user role operation.

	Typically these are written to a http.Request.
*/
type GetV1UserRoleParams struct {

	// XAuthToken.
	XAuthToken string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get v1 user role params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1UserRoleParams) WithDefaults() *GetV1UserRoleParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get v1 user role params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1UserRoleParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get v1 user role params
func (o *GetV1UserRoleParams) WithTimeout(timeout time.Duration) *GetV1UserRoleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1 user role params
func (o *GetV1UserRoleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1 user role params
func (o *GetV1UserRoleParams) WithContext(ctx context.Context) *GetV1UserRoleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1 user role params
func (o *GetV1UserRoleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1 user role params
func (o *GetV1UserRoleParams) WithHTTPClient(client *http.Client) *GetV1UserRoleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1 user role params
func (o *GetV1UserRoleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAuthToken adds the xAuthToken to the get v1 user role params
func (o *GetV1UserRoleParams) WithXAuthToken(xAuthToken string) *GetV1UserRoleParams {
	o.SetXAuthToken(xAuthToken)
	return o
}

// SetXAuthToken adds the xAuthToken to the get v1 user role params
func (o *GetV1UserRoleParams) SetXAuthToken(xAuthToken string) {
	o.XAuthToken = xAuthToken
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1UserRoleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Auth-Token
	if err := r.SetHeaderParam("X-Auth-Token", o.XAuthToken); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
