// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostV1UserFullnamePasswordReader is a Reader for the PostV1UserFullnamePassword structure.
type PostV1UserFullnamePasswordReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostV1UserFullnamePasswordReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostV1UserFullnamePasswordOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /v1/user/{fullname}/password] PostV1UserFullnamePassword", response, response.Code())
	}
}

// NewPostV1UserFullnamePasswordOK creates a PostV1UserFullnamePasswordOK with default headers values
func NewPostV1UserFullnamePasswordOK() *PostV1UserFullnamePasswordOK {
	return &PostV1UserFullnamePasswordOK{}
}

/*
PostV1UserFullnamePasswordOK describes a response with status code 200, with default header values.

Success
*/
type PostV1UserFullnamePasswordOK struct {
}

// IsSuccess returns true when this post v1 user fullname password o k response has a 2xx status code
func (o *PostV1UserFullnamePasswordOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post v1 user fullname password o k response has a 3xx status code
func (o *PostV1UserFullnamePasswordOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post v1 user fullname password o k response has a 4xx status code
func (o *PostV1UserFullnamePasswordOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post v1 user fullname password o k response has a 5xx status code
func (o *PostV1UserFullnamePasswordOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post v1 user fullname password o k response a status code equal to that given
func (o *PostV1UserFullnamePasswordOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post v1 user fullname password o k response
func (o *PostV1UserFullnamePasswordOK) Code() int {
	return 200
}

func (o *PostV1UserFullnamePasswordOK) Error() string {
	return fmt.Sprintf("[POST /v1/user/{fullname}/password][%d] postV1UserFullnamePasswordOK ", 200)
}

func (o *PostV1UserFullnamePasswordOK) String() string {
	return fmt.Sprintf("[POST /v1/user/{fullname}/password][%d] postV1UserFullnamePasswordOK ", 200)
}

func (o *PostV1UserFullnamePasswordOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
