// Code generated by go-swagger; DO NOT EDIT.

package controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetV1ControllerIDConfigParams creates a new GetV1ControllerIDConfigParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetV1ControllerIDConfigParams() *GetV1ControllerIDConfigParams {
	return &GetV1ControllerIDConfigParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1ControllerIDConfigParamsWithTimeout creates a new GetV1ControllerIDConfigParams object
// with the ability to set a timeout on a request.
func NewGetV1ControllerIDConfigParamsWithTimeout(timeout time.Duration) *GetV1ControllerIDConfigParams {
	return &GetV1ControllerIDConfigParams{
		timeout: timeout,
	}
}

// NewGetV1ControllerIDConfigParamsWithContext creates a new GetV1ControllerIDConfigParams object
// with the ability to set a context for a request.
func NewGetV1ControllerIDConfigParamsWithContext(ctx context.Context) *GetV1ControllerIDConfigParams {
	return &GetV1ControllerIDConfigParams{
		Context: ctx,
	}
}

// NewGetV1ControllerIDConfigParamsWithHTTPClient creates a new GetV1ControllerIDConfigParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetV1ControllerIDConfigParamsWithHTTPClient(client *http.Client) *GetV1ControllerIDConfigParams {
	return &GetV1ControllerIDConfigParams{
		HTTPClient: client,
	}
}

/*
GetV1ControllerIDConfigParams contains all the parameters to send to the API endpoint

	for the get v1 controller ID config operation.

	Typically these are written to a http.Request.
*/
type GetV1ControllerIDConfigParams struct {

	/* ID.

	   Controller ID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get v1 controller ID config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1ControllerIDConfigParams) WithDefaults() *GetV1ControllerIDConfigParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get v1 controller ID config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1ControllerIDConfigParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get v1 controller ID config params
func (o *GetV1ControllerIDConfigParams) WithTimeout(timeout time.Duration) *GetV1ControllerIDConfigParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1 controller ID config params
func (o *GetV1ControllerIDConfigParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1 controller ID config params
func (o *GetV1ControllerIDConfigParams) WithContext(ctx context.Context) *GetV1ControllerIDConfigParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1 controller ID config params
func (o *GetV1ControllerIDConfigParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1 controller ID config params
func (o *GetV1ControllerIDConfigParams) WithHTTPClient(client *http.Client) *GetV1ControllerIDConfigParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1 controller ID config params
func (o *GetV1ControllerIDConfigParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get v1 controller ID config params
func (o *GetV1ControllerIDConfigParams) WithID(id string) *GetV1ControllerIDConfigParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get v1 controller ID config params
func (o *GetV1ControllerIDConfigParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1ControllerIDConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
