// Code generated by go-swagger; DO NOT EDIT.

package controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetV1ControllerIDParams creates a new GetV1ControllerIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetV1ControllerIDParams() *GetV1ControllerIDParams {
	return &GetV1ControllerIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1ControllerIDParamsWithTimeout creates a new GetV1ControllerIDParams object
// with the ability to set a timeout on a request.
func NewGetV1ControllerIDParamsWithTimeout(timeout time.Duration) *GetV1ControllerIDParams {
	return &GetV1ControllerIDParams{
		timeout: timeout,
	}
}

// NewGetV1ControllerIDParamsWithContext creates a new GetV1ControllerIDParams object
// with the ability to set a context for a request.
func NewGetV1ControllerIDParamsWithContext(ctx context.Context) *GetV1ControllerIDParams {
	return &GetV1ControllerIDParams{
		Context: ctx,
	}
}

// NewGetV1ControllerIDParamsWithHTTPClient creates a new GetV1ControllerIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetV1ControllerIDParamsWithHTTPClient(client *http.Client) *GetV1ControllerIDParams {
	return &GetV1ControllerIDParams{
		HTTPClient: client,
	}
}

/*
GetV1ControllerIDParams contains all the parameters to send to the API endpoint

	for the get v1 controller ID operation.

	Typically these are written to a http.Request.
*/
type GetV1ControllerIDParams struct {

	// XAuthToken.
	XAuthToken string

	/* ID.

	   Controller ID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get v1 controller ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1ControllerIDParams) WithDefaults() *GetV1ControllerIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get v1 controller ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1ControllerIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get v1 controller ID params
func (o *GetV1ControllerIDParams) WithTimeout(timeout time.Duration) *GetV1ControllerIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1 controller ID params
func (o *GetV1ControllerIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1 controller ID params
func (o *GetV1ControllerIDParams) WithContext(ctx context.Context) *GetV1ControllerIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1 controller ID params
func (o *GetV1ControllerIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1 controller ID params
func (o *GetV1ControllerIDParams) WithHTTPClient(client *http.Client) *GetV1ControllerIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1 controller ID params
func (o *GetV1ControllerIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAuthToken adds the xAuthToken to the get v1 controller ID params
func (o *GetV1ControllerIDParams) WithXAuthToken(xAuthToken string) *GetV1ControllerIDParams {
	o.SetXAuthToken(xAuthToken)
	return o
}

// SetXAuthToken adds the xAuthToken to the get v1 controller ID params
func (o *GetV1ControllerIDParams) SetXAuthToken(xAuthToken string) {
	o.XAuthToken = xAuthToken
}

// WithID adds the id to the get v1 controller ID params
func (o *GetV1ControllerIDParams) WithID(id string) *GetV1ControllerIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get v1 controller ID params
func (o *GetV1ControllerIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1ControllerIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Auth-Token
	if err := r.SetHeaderParam("X-Auth-Token", o.XAuthToken); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
