// Code generated by go-swagger; DO NOT EDIT.

package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/minchao/neuvector-sdk/models"
)

// GetV1SystemSummaryReader is a Reader for the GetV1SystemSummary structure.
type GetV1SystemSummaryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetV1SystemSummaryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetV1SystemSummaryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /v1/system/summary] GetV1SystemSummary", response, response.Code())
	}
}

// NewGetV1SystemSummaryOK creates a GetV1SystemSummaryOK with default headers values
func NewGetV1SystemSummaryOK() *GetV1SystemSummaryOK {
	return &GetV1SystemSummaryOK{}
}

/*
GetV1SystemSummaryOK describes a response with status code 200, with default header values.

Success
*/
type GetV1SystemSummaryOK struct {
	Payload *models.RESTSystemSummaryData
}

// IsSuccess returns true when this get v1 system summary o k response has a 2xx status code
func (o *GetV1SystemSummaryOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get v1 system summary o k response has a 3xx status code
func (o *GetV1SystemSummaryOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 system summary o k response has a 4xx status code
func (o *GetV1SystemSummaryOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get v1 system summary o k response has a 5xx status code
func (o *GetV1SystemSummaryOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get v1 system summary o k response a status code equal to that given
func (o *GetV1SystemSummaryOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get v1 system summary o k response
func (o *GetV1SystemSummaryOK) Code() int {
	return 200
}

func (o *GetV1SystemSummaryOK) Error() string {
	return fmt.Sprintf("[GET /v1/system/summary][%d] getV1SystemSummaryOK  %+v", 200, o.Payload)
}

func (o *GetV1SystemSummaryOK) String() string {
	return fmt.Sprintf("[GET /v1/system/summary][%d] getV1SystemSummaryOK  %+v", 200, o.Payload)
}

func (o *GetV1SystemSummaryOK) GetPayload() *models.RESTSystemSummaryData {
	return o.Payload
}

func (o *GetV1SystemSummaryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RESTSystemSummaryData)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
