// Code generated by go-swagger; DO NOT EDIT.

package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PatchV1SystemConfigWebhookNameReader is a Reader for the PatchV1SystemConfigWebhookName structure.
type PatchV1SystemConfigWebhookNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchV1SystemConfigWebhookNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPatchV1SystemConfigWebhookNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PATCH /v1/system/config/webhook/{name}] PatchV1SystemConfigWebhookName", response, response.Code())
	}
}

// NewPatchV1SystemConfigWebhookNameOK creates a PatchV1SystemConfigWebhookNameOK with default headers values
func NewPatchV1SystemConfigWebhookNameOK() *PatchV1SystemConfigWebhookNameOK {
	return &PatchV1SystemConfigWebhookNameOK{}
}

/*
PatchV1SystemConfigWebhookNameOK describes a response with status code 200, with default header values.

Success
*/
type PatchV1SystemConfigWebhookNameOK struct {
}

// IsSuccess returns true when this patch v1 system config webhook name o k response has a 2xx status code
func (o *PatchV1SystemConfigWebhookNameOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this patch v1 system config webhook name o k response has a 3xx status code
func (o *PatchV1SystemConfigWebhookNameOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this patch v1 system config webhook name o k response has a 4xx status code
func (o *PatchV1SystemConfigWebhookNameOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this patch v1 system config webhook name o k response has a 5xx status code
func (o *PatchV1SystemConfigWebhookNameOK) IsServerError() bool {
	return false
}

// IsCode returns true when this patch v1 system config webhook name o k response a status code equal to that given
func (o *PatchV1SystemConfigWebhookNameOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the patch v1 system config webhook name o k response
func (o *PatchV1SystemConfigWebhookNameOK) Code() int {
	return 200
}

func (o *PatchV1SystemConfigWebhookNameOK) Error() string {
	return fmt.Sprintf("[PATCH /v1/system/config/webhook/{name}][%d] patchV1SystemConfigWebhookNameOK ", 200)
}

func (o *PatchV1SystemConfigWebhookNameOK) String() string {
	return fmt.Sprintf("[PATCH /v1/system/config/webhook/{name}][%d] patchV1SystemConfigWebhookNameOK ", 200)
}

func (o *PatchV1SystemConfigWebhookNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
