// Code generated by go-swagger; DO NOT EDIT.

package d_l_p

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteV1DlpSensorNameReader is a Reader for the DeleteV1DlpSensorName structure.
type DeleteV1DlpSensorNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteV1DlpSensorNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteV1DlpSensorNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /v1/dlp/sensor/{name}] DeleteV1DlpSensorName", response, response.Code())
	}
}

// NewDeleteV1DlpSensorNameOK creates a DeleteV1DlpSensorNameOK with default headers values
func NewDeleteV1DlpSensorNameOK() *DeleteV1DlpSensorNameOK {
	return &DeleteV1DlpSensorNameOK{}
}

/*
DeleteV1DlpSensorNameOK describes a response with status code 200, with default header values.

Success
*/
type DeleteV1DlpSensorNameOK struct {
}

// IsSuccess returns true when this delete v1 dlp sensor name o k response has a 2xx status code
func (o *DeleteV1DlpSensorNameOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete v1 dlp sensor name o k response has a 3xx status code
func (o *DeleteV1DlpSensorNameOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete v1 dlp sensor name o k response has a 4xx status code
func (o *DeleteV1DlpSensorNameOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete v1 dlp sensor name o k response has a 5xx status code
func (o *DeleteV1DlpSensorNameOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete v1 dlp sensor name o k response a status code equal to that given
func (o *DeleteV1DlpSensorNameOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete v1 dlp sensor name o k response
func (o *DeleteV1DlpSensorNameOK) Code() int {
	return 200
}

func (o *DeleteV1DlpSensorNameOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/dlp/sensor/{name}][%d] deleteV1DlpSensorNameOK ", 200)
}

func (o *DeleteV1DlpSensorNameOK) String() string {
	return fmt.Sprintf("[DELETE /v1/dlp/sensor/{name}][%d] deleteV1DlpSensorNameOK ", 200)
}

func (o *DeleteV1DlpSensorNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
