// Code generated by go-swagger; DO NOT EDIT.

package d_l_p

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/minchao/neuvector-sdk/models"
)

// GetV1DlpGroupReader is a Reader for the GetV1DlpGroup structure.
type GetV1DlpGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetV1DlpGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetV1DlpGroupOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /v1/dlp/group] GetV1DlpGroup", response, response.Code())
	}
}

// NewGetV1DlpGroupOK creates a GetV1DlpGroupOK with default headers values
func NewGetV1DlpGroupOK() *GetV1DlpGroupOK {
	return &GetV1DlpGroupOK{}
}

/*
GetV1DlpGroupOK describes a response with status code 200, with default header values.

Success
*/
type GetV1DlpGroupOK struct {
	Payload *models.RESTDlpGroupsData
}

// IsSuccess returns true when this get v1 dlp group o k response has a 2xx status code
func (o *GetV1DlpGroupOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get v1 dlp group o k response has a 3xx status code
func (o *GetV1DlpGroupOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 dlp group o k response has a 4xx status code
func (o *GetV1DlpGroupOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get v1 dlp group o k response has a 5xx status code
func (o *GetV1DlpGroupOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get v1 dlp group o k response a status code equal to that given
func (o *GetV1DlpGroupOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get v1 dlp group o k response
func (o *GetV1DlpGroupOK) Code() int {
	return 200
}

func (o *GetV1DlpGroupOK) Error() string {
	return fmt.Sprintf("[GET /v1/dlp/group][%d] getV1DlpGroupOK  %+v", 200, o.Payload)
}

func (o *GetV1DlpGroupOK) String() string {
	return fmt.Sprintf("[GET /v1/dlp/group][%d] getV1DlpGroupOK  %+v", 200, o.Payload)
}

func (o *GetV1DlpGroupOK) GetPayload() *models.RESTDlpGroupsData {
	return o.Payload
}

func (o *GetV1DlpGroupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RESTDlpGroupsData)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
