// Code generated by go-swagger; DO NOT EDIT.

package d_l_p

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/minchao/neuvector-sdk/models"
)

// NewPatchV1DlpGroupNameParams creates a new PatchV1DlpGroupNameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPatchV1DlpGroupNameParams() *PatchV1DlpGroupNameParams {
	return &PatchV1DlpGroupNameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPatchV1DlpGroupNameParamsWithTimeout creates a new PatchV1DlpGroupNameParams object
// with the ability to set a timeout on a request.
func NewPatchV1DlpGroupNameParamsWithTimeout(timeout time.Duration) *PatchV1DlpGroupNameParams {
	return &PatchV1DlpGroupNameParams{
		timeout: timeout,
	}
}

// NewPatchV1DlpGroupNameParamsWithContext creates a new PatchV1DlpGroupNameParams object
// with the ability to set a context for a request.
func NewPatchV1DlpGroupNameParamsWithContext(ctx context.Context) *PatchV1DlpGroupNameParams {
	return &PatchV1DlpGroupNameParams{
		Context: ctx,
	}
}

// NewPatchV1DlpGroupNameParamsWithHTTPClient creates a new PatchV1DlpGroupNameParams object
// with the ability to set a custom HTTPClient for a request.
func NewPatchV1DlpGroupNameParamsWithHTTPClient(client *http.Client) *PatchV1DlpGroupNameParams {
	return &PatchV1DlpGroupNameParams{
		HTTPClient: client,
	}
}

/*
PatchV1DlpGroupNameParams contains all the parameters to send to the API endpoint

	for the patch v1 dlp group name operation.

	Typically these are written to a http.Request.
*/
type PatchV1DlpGroupNameParams struct {

	/* Body.

	   DLP group data
	*/
	Body *models.RESTDlpGroupConfigData

	/* Name.

	   DLP group name
	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the patch v1 dlp group name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchV1DlpGroupNameParams) WithDefaults() *PatchV1DlpGroupNameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the patch v1 dlp group name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchV1DlpGroupNameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the patch v1 dlp group name params
func (o *PatchV1DlpGroupNameParams) WithTimeout(timeout time.Duration) *PatchV1DlpGroupNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch v1 dlp group name params
func (o *PatchV1DlpGroupNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch v1 dlp group name params
func (o *PatchV1DlpGroupNameParams) WithContext(ctx context.Context) *PatchV1DlpGroupNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch v1 dlp group name params
func (o *PatchV1DlpGroupNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch v1 dlp group name params
func (o *PatchV1DlpGroupNameParams) WithHTTPClient(client *http.Client) *PatchV1DlpGroupNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch v1 dlp group name params
func (o *PatchV1DlpGroupNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the patch v1 dlp group name params
func (o *PatchV1DlpGroupNameParams) WithBody(body *models.RESTDlpGroupConfigData) *PatchV1DlpGroupNameParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the patch v1 dlp group name params
func (o *PatchV1DlpGroupNameParams) SetBody(body *models.RESTDlpGroupConfigData) {
	o.Body = body
}

// WithName adds the name to the patch v1 dlp group name params
func (o *PatchV1DlpGroupNameParams) WithName(name string) *PatchV1DlpGroupNameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the patch v1 dlp group name params
func (o *PatchV1DlpGroupNameParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *PatchV1DlpGroupNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
