// Code generated by go-swagger; DO NOT EDIT.

package authentication

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PatchV1AuthReader is a Reader for the PatchV1Auth structure.
type PatchV1AuthReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchV1AuthReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPatchV1AuthOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PATCH /v1/auth] PatchV1Auth", response, response.Code())
	}
}

// NewPatchV1AuthOK creates a PatchV1AuthOK with default headers values
func NewPatchV1AuthOK() *PatchV1AuthOK {
	return &PatchV1AuthOK{}
}

/*
PatchV1AuthOK describes a response with status code 200, with default header values.

Success
*/
type PatchV1AuthOK struct {
}

// IsSuccess returns true when this patch v1 auth o k response has a 2xx status code
func (o *PatchV1AuthOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this patch v1 auth o k response has a 3xx status code
func (o *PatchV1AuthOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this patch v1 auth o k response has a 4xx status code
func (o *PatchV1AuthOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this patch v1 auth o k response has a 5xx status code
func (o *PatchV1AuthOK) IsServerError() bool {
	return false
}

// IsCode returns true when this patch v1 auth o k response a status code equal to that given
func (o *PatchV1AuthOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the patch v1 auth o k response
func (o *PatchV1AuthOK) Code() int {
	return 200
}

func (o *PatchV1AuthOK) Error() string {
	return fmt.Sprintf("[PATCH /v1/auth][%d] patchV1AuthOK ", 200)
}

func (o *PatchV1AuthOK) String() string {
	return fmt.Sprintf("[PATCH /v1/auth][%d] patchV1AuthOK ", 200)
}

func (o *PatchV1AuthOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
