// Code generated by go-swagger; DO NOT EDIT.

package authentication

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostV1AuthServerReader is a Reader for the PostV1AuthServer structure.
type PostV1AuthServerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostV1AuthServerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostV1AuthServerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /v1/auth/{server}] PostV1AuthServer", response, response.Code())
	}
}

// NewPostV1AuthServerOK creates a PostV1AuthServerOK with default headers values
func NewPostV1AuthServerOK() *PostV1AuthServerOK {
	return &PostV1AuthServerOK{}
}

/*
PostV1AuthServerOK describes a response with status code 200, with default header values.

Success
*/
type PostV1AuthServerOK struct {
}

// IsSuccess returns true when this post v1 auth server o k response has a 2xx status code
func (o *PostV1AuthServerOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post v1 auth server o k response has a 3xx status code
func (o *PostV1AuthServerOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post v1 auth server o k response has a 4xx status code
func (o *PostV1AuthServerOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post v1 auth server o k response has a 5xx status code
func (o *PostV1AuthServerOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post v1 auth server o k response a status code equal to that given
func (o *PostV1AuthServerOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post v1 auth server o k response
func (o *PostV1AuthServerOK) Code() int {
	return 200
}

func (o *PostV1AuthServerOK) Error() string {
	return fmt.Sprintf("[POST /v1/auth/{server}][%d] postV1AuthServerOK ", 200)
}

func (o *PostV1AuthServerOK) String() string {
	return fmt.Sprintf("[POST /v1/auth/{server}][%d] postV1AuthServerOK ", 200)
}

func (o *PostV1AuthServerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
