// Code generated by go-swagger; DO NOT EDIT.

package admission

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteV1AdmissionRuleIDReader is a Reader for the DeleteV1AdmissionRuleID structure.
type DeleteV1AdmissionRuleIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteV1AdmissionRuleIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteV1AdmissionRuleIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /v1/admission/rule/{id}] DeleteV1AdmissionRuleID", response, response.Code())
	}
}

// NewDeleteV1AdmissionRuleIDOK creates a DeleteV1AdmissionRuleIDOK with default headers values
func NewDeleteV1AdmissionRuleIDOK() *DeleteV1AdmissionRuleIDOK {
	return &DeleteV1AdmissionRuleIDOK{}
}

/*
DeleteV1AdmissionRuleIDOK describes a response with status code 200, with default header values.

Success
*/
type DeleteV1AdmissionRuleIDOK struct {
}

// IsSuccess returns true when this delete v1 admission rule Id o k response has a 2xx status code
func (o *DeleteV1AdmissionRuleIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete v1 admission rule Id o k response has a 3xx status code
func (o *DeleteV1AdmissionRuleIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete v1 admission rule Id o k response has a 4xx status code
func (o *DeleteV1AdmissionRuleIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete v1 admission rule Id o k response has a 5xx status code
func (o *DeleteV1AdmissionRuleIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete v1 admission rule Id o k response a status code equal to that given
func (o *DeleteV1AdmissionRuleIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete v1 admission rule Id o k response
func (o *DeleteV1AdmissionRuleIDOK) Code() int {
	return 200
}

func (o *DeleteV1AdmissionRuleIDOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/admission/rule/{id}][%d] deleteV1AdmissionRuleIdOK ", 200)
}

func (o *DeleteV1AdmissionRuleIDOK) String() string {
	return fmt.Sprintf("[DELETE /v1/admission/rule/{id}][%d] deleteV1AdmissionRuleIdOK ", 200)
}

func (o *DeleteV1AdmissionRuleIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
