// Code generated by go-swagger; DO NOT EDIT.

package admission

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/minchao/neuvector-sdk/models"
)

// GetV1AdmissionRuleIDReader is a Reader for the GetV1AdmissionRuleID structure.
type GetV1AdmissionRuleIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetV1AdmissionRuleIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetV1AdmissionRuleIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /v1/admission/rule/{id}] GetV1AdmissionRuleID", response, response.Code())
	}
}

// NewGetV1AdmissionRuleIDOK creates a GetV1AdmissionRuleIDOK with default headers values
func NewGetV1AdmissionRuleIDOK() *GetV1AdmissionRuleIDOK {
	return &GetV1AdmissionRuleIDOK{}
}

/*
GetV1AdmissionRuleIDOK describes a response with status code 200, with default header values.

Success
*/
type GetV1AdmissionRuleIDOK struct {
	Payload *models.RESTAdmissionRuleData
}

// IsSuccess returns true when this get v1 admission rule Id o k response has a 2xx status code
func (o *GetV1AdmissionRuleIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get v1 admission rule Id o k response has a 3xx status code
func (o *GetV1AdmissionRuleIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 admission rule Id o k response has a 4xx status code
func (o *GetV1AdmissionRuleIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get v1 admission rule Id o k response has a 5xx status code
func (o *GetV1AdmissionRuleIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get v1 admission rule Id o k response a status code equal to that given
func (o *GetV1AdmissionRuleIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get v1 admission rule Id o k response
func (o *GetV1AdmissionRuleIDOK) Code() int {
	return 200
}

func (o *GetV1AdmissionRuleIDOK) Error() string {
	return fmt.Sprintf("[GET /v1/admission/rule/{id}][%d] getV1AdmissionRuleIdOK  %+v", 200, o.Payload)
}

func (o *GetV1AdmissionRuleIDOK) String() string {
	return fmt.Sprintf("[GET /v1/admission/rule/{id}][%d] getV1AdmissionRuleIdOK  %+v", 200, o.Payload)
}

func (o *GetV1AdmissionRuleIDOK) GetPayload() *models.RESTAdmissionRuleData {
	return o.Payload
}

func (o *GetV1AdmissionRuleIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RESTAdmissionRuleData)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
