// Code generated by go-swagger; DO NOT EDIT.

package admission

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetV1AdmissionStatsParams creates a new GetV1AdmissionStatsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetV1AdmissionStatsParams() *GetV1AdmissionStatsParams {
	return &GetV1AdmissionStatsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1AdmissionStatsParamsWithTimeout creates a new GetV1AdmissionStatsParams object
// with the ability to set a timeout on a request.
func NewGetV1AdmissionStatsParamsWithTimeout(timeout time.Duration) *GetV1AdmissionStatsParams {
	return &GetV1AdmissionStatsParams{
		timeout: timeout,
	}
}

// NewGetV1AdmissionStatsParamsWithContext creates a new GetV1AdmissionStatsParams object
// with the ability to set a context for a request.
func NewGetV1AdmissionStatsParamsWithContext(ctx context.Context) *GetV1AdmissionStatsParams {
	return &GetV1AdmissionStatsParams{
		Context: ctx,
	}
}

// NewGetV1AdmissionStatsParamsWithHTTPClient creates a new GetV1AdmissionStatsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetV1AdmissionStatsParamsWithHTTPClient(client *http.Client) *GetV1AdmissionStatsParams {
	return &GetV1AdmissionStatsParams{
		HTTPClient: client,
	}
}

/*
GetV1AdmissionStatsParams contains all the parameters to send to the API endpoint

	for the get v1 admission stats operation.

	Typically these are written to a http.Request.
*/
type GetV1AdmissionStatsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get v1 admission stats params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1AdmissionStatsParams) WithDefaults() *GetV1AdmissionStatsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get v1 admission stats params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1AdmissionStatsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get v1 admission stats params
func (o *GetV1AdmissionStatsParams) WithTimeout(timeout time.Duration) *GetV1AdmissionStatsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1 admission stats params
func (o *GetV1AdmissionStatsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1 admission stats params
func (o *GetV1AdmissionStatsParams) WithContext(ctx context.Context) *GetV1AdmissionStatsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1 admission stats params
func (o *GetV1AdmissionStatsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1 admission stats params
func (o *GetV1AdmissionStatsParams) WithHTTPClient(client *http.Client) *GetV1AdmissionStatsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1 admission stats params
func (o *GetV1AdmissionStatsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1AdmissionStatsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
