// Code generated by go-swagger; DO NOT EDIT.

package admission

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/minchao/neuvector-sdk/models"
)

// NewPatchV1AdmissionStateParams creates a new PatchV1AdmissionStateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPatchV1AdmissionStateParams() *PatchV1AdmissionStateParams {
	return &PatchV1AdmissionStateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPatchV1AdmissionStateParamsWithTimeout creates a new PatchV1AdmissionStateParams object
// with the ability to set a timeout on a request.
func NewPatchV1AdmissionStateParamsWithTimeout(timeout time.Duration) *PatchV1AdmissionStateParams {
	return &PatchV1AdmissionStateParams{
		timeout: timeout,
	}
}

// NewPatchV1AdmissionStateParamsWithContext creates a new PatchV1AdmissionStateParams object
// with the ability to set a context for a request.
func NewPatchV1AdmissionStateParamsWithContext(ctx context.Context) *PatchV1AdmissionStateParams {
	return &PatchV1AdmissionStateParams{
		Context: ctx,
	}
}

// NewPatchV1AdmissionStateParamsWithHTTPClient creates a new PatchV1AdmissionStateParams object
// with the ability to set a custom HTTPClient for a request.
func NewPatchV1AdmissionStateParamsWithHTTPClient(client *http.Client) *PatchV1AdmissionStateParams {
	return &PatchV1AdmissionStateParams{
		HTTPClient: client,
	}
}

/*
PatchV1AdmissionStateParams contains all the parameters to send to the API endpoint

	for the patch v1 admission state operation.

	Typically these are written to a http.Request.
*/
type PatchV1AdmissionStateParams struct {

	// XAuthToken.
	XAuthToken string

	/* Body.

	   Admission config state data
	*/
	Body *models.RESTAdmissionConfigData

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the patch v1 admission state params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchV1AdmissionStateParams) WithDefaults() *PatchV1AdmissionStateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the patch v1 admission state params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchV1AdmissionStateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the patch v1 admission state params
func (o *PatchV1AdmissionStateParams) WithTimeout(timeout time.Duration) *PatchV1AdmissionStateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch v1 admission state params
func (o *PatchV1AdmissionStateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch v1 admission state params
func (o *PatchV1AdmissionStateParams) WithContext(ctx context.Context) *PatchV1AdmissionStateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch v1 admission state params
func (o *PatchV1AdmissionStateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch v1 admission state params
func (o *PatchV1AdmissionStateParams) WithHTTPClient(client *http.Client) *PatchV1AdmissionStateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch v1 admission state params
func (o *PatchV1AdmissionStateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAuthToken adds the xAuthToken to the patch v1 admission state params
func (o *PatchV1AdmissionStateParams) WithXAuthToken(xAuthToken string) *PatchV1AdmissionStateParams {
	o.SetXAuthToken(xAuthToken)
	return o
}

// SetXAuthToken adds the xAuthToken to the patch v1 admission state params
func (o *PatchV1AdmissionStateParams) SetXAuthToken(xAuthToken string) {
	o.XAuthToken = xAuthToken
}

// WithBody adds the body to the patch v1 admission state params
func (o *PatchV1AdmissionStateParams) WithBody(body *models.RESTAdmissionConfigData) *PatchV1AdmissionStateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the patch v1 admission state params
func (o *PatchV1AdmissionStateParams) SetBody(body *models.RESTAdmissionConfigData) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PatchV1AdmissionStateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Auth-Token
	if err := r.SetHeaderParam("X-Auth-Token", o.XAuthToken); err != nil {
		return err
	}
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
