// Code generated by go-swagger; DO NOT EDIT.

package admission

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/minchao/neuvector-sdk/models"
)

// NewPostV1AdmissionRulePromoteParams creates a new PostV1AdmissionRulePromoteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostV1AdmissionRulePromoteParams() *PostV1AdmissionRulePromoteParams {
	return &PostV1AdmissionRulePromoteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostV1AdmissionRulePromoteParamsWithTimeout creates a new PostV1AdmissionRulePromoteParams object
// with the ability to set a timeout on a request.
func NewPostV1AdmissionRulePromoteParamsWithTimeout(timeout time.Duration) *PostV1AdmissionRulePromoteParams {
	return &PostV1AdmissionRulePromoteParams{
		timeout: timeout,
	}
}

// NewPostV1AdmissionRulePromoteParamsWithContext creates a new PostV1AdmissionRulePromoteParams object
// with the ability to set a context for a request.
func NewPostV1AdmissionRulePromoteParamsWithContext(ctx context.Context) *PostV1AdmissionRulePromoteParams {
	return &PostV1AdmissionRulePromoteParams{
		Context: ctx,
	}
}

// NewPostV1AdmissionRulePromoteParamsWithHTTPClient creates a new PostV1AdmissionRulePromoteParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostV1AdmissionRulePromoteParamsWithHTTPClient(client *http.Client) *PostV1AdmissionRulePromoteParams {
	return &PostV1AdmissionRulePromoteParams{
		HTTPClient: client,
	}
}

/*
PostV1AdmissionRulePromoteParams contains all the parameters to send to the API endpoint

	for the post v1 admission rule promote operation.

	Typically these are written to a http.Request.
*/
type PostV1AdmissionRulePromoteParams struct {

	// XAuthToken.
	XAuthToken string

	/* Body.

	   Admission control rule data
	*/
	Body *models.RESTAdmCtrlPromoteRequestData

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post v1 admission rule promote params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostV1AdmissionRulePromoteParams) WithDefaults() *PostV1AdmissionRulePromoteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post v1 admission rule promote params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostV1AdmissionRulePromoteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post v1 admission rule promote params
func (o *PostV1AdmissionRulePromoteParams) WithTimeout(timeout time.Duration) *PostV1AdmissionRulePromoteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post v1 admission rule promote params
func (o *PostV1AdmissionRulePromoteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post v1 admission rule promote params
func (o *PostV1AdmissionRulePromoteParams) WithContext(ctx context.Context) *PostV1AdmissionRulePromoteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post v1 admission rule promote params
func (o *PostV1AdmissionRulePromoteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post v1 admission rule promote params
func (o *PostV1AdmissionRulePromoteParams) WithHTTPClient(client *http.Client) *PostV1AdmissionRulePromoteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post v1 admission rule promote params
func (o *PostV1AdmissionRulePromoteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAuthToken adds the xAuthToken to the post v1 admission rule promote params
func (o *PostV1AdmissionRulePromoteParams) WithXAuthToken(xAuthToken string) *PostV1AdmissionRulePromoteParams {
	o.SetXAuthToken(xAuthToken)
	return o
}

// SetXAuthToken adds the xAuthToken to the post v1 admission rule promote params
func (o *PostV1AdmissionRulePromoteParams) SetXAuthToken(xAuthToken string) {
	o.XAuthToken = xAuthToken
}

// WithBody adds the body to the post v1 admission rule promote params
func (o *PostV1AdmissionRulePromoteParams) WithBody(body *models.RESTAdmCtrlPromoteRequestData) *PostV1AdmissionRulePromoteParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post v1 admission rule promote params
func (o *PostV1AdmissionRulePromoteParams) SetBody(body *models.RESTAdmCtrlPromoteRequestData) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostV1AdmissionRulePromoteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Auth-Token
	if err := r.SetHeaderParam("X-Auth-Token", o.XAuthToken); err != nil {
		return err
	}
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
