// Code generated by go-swagger; DO NOT EDIT.

package group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteV1GroupNameParams creates a new DeleteV1GroupNameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteV1GroupNameParams() *DeleteV1GroupNameParams {
	return &DeleteV1GroupNameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteV1GroupNameParamsWithTimeout creates a new DeleteV1GroupNameParams object
// with the ability to set a timeout on a request.
func NewDeleteV1GroupNameParamsWithTimeout(timeout time.Duration) *DeleteV1GroupNameParams {
	return &DeleteV1GroupNameParams{
		timeout: timeout,
	}
}

// NewDeleteV1GroupNameParamsWithContext creates a new DeleteV1GroupNameParams object
// with the ability to set a context for a request.
func NewDeleteV1GroupNameParamsWithContext(ctx context.Context) *DeleteV1GroupNameParams {
	return &DeleteV1GroupNameParams{
		Context: ctx,
	}
}

// NewDeleteV1GroupNameParamsWithHTTPClient creates a new DeleteV1GroupNameParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteV1GroupNameParamsWithHTTPClient(client *http.Client) *DeleteV1GroupNameParams {
	return &DeleteV1GroupNameParams{
		HTTPClient: client,
	}
}

/*
DeleteV1GroupNameParams contains all the parameters to send to the API endpoint

	for the delete v1 group name operation.

	Typically these are written to a http.Request.
*/
type DeleteV1GroupNameParams struct {

	// XAuthToken.
	XAuthToken string

	/* Name.

	   Group name
	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete v1 group name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteV1GroupNameParams) WithDefaults() *DeleteV1GroupNameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete v1 group name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteV1GroupNameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete v1 group name params
func (o *DeleteV1GroupNameParams) WithTimeout(timeout time.Duration) *DeleteV1GroupNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete v1 group name params
func (o *DeleteV1GroupNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete v1 group name params
func (o *DeleteV1GroupNameParams) WithContext(ctx context.Context) *DeleteV1GroupNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete v1 group name params
func (o *DeleteV1GroupNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete v1 group name params
func (o *DeleteV1GroupNameParams) WithHTTPClient(client *http.Client) *DeleteV1GroupNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete v1 group name params
func (o *DeleteV1GroupNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAuthToken adds the xAuthToken to the delete v1 group name params
func (o *DeleteV1GroupNameParams) WithXAuthToken(xAuthToken string) *DeleteV1GroupNameParams {
	o.SetXAuthToken(xAuthToken)
	return o
}

// SetXAuthToken adds the xAuthToken to the delete v1 group name params
func (o *DeleteV1GroupNameParams) SetXAuthToken(xAuthToken string) {
	o.XAuthToken = xAuthToken
}

// WithName adds the name to the delete v1 group name params
func (o *DeleteV1GroupNameParams) WithName(name string) *DeleteV1GroupNameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the delete v1 group name params
func (o *DeleteV1GroupNameParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteV1GroupNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Auth-Token
	if err := r.SetHeaderParam("X-Auth-Token", o.XAuthToken); err != nil {
		return err
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
