// Code generated by go-swagger; DO NOT EDIT.

package file

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostV1FileConfigReader is a Reader for the PostV1FileConfig structure.
type PostV1FileConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostV1FileConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostV1FileConfigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /v1/file/config] PostV1FileConfig", response, response.Code())
	}
}

// NewPostV1FileConfigOK creates a PostV1FileConfigOK with default headers values
func NewPostV1FileConfigOK() *PostV1FileConfigOK {
	return &PostV1FileConfigOK{}
}

/*
PostV1FileConfigOK describes a response with status code 200, with default header values.

Success. Upload a configure file.
*/
type PostV1FileConfigOK struct {
}

// IsSuccess returns true when this post v1 file config o k response has a 2xx status code
func (o *PostV1FileConfigOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post v1 file config o k response has a 3xx status code
func (o *PostV1FileConfigOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post v1 file config o k response has a 4xx status code
func (o *PostV1FileConfigOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post v1 file config o k response has a 5xx status code
func (o *PostV1FileConfigOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post v1 file config o k response a status code equal to that given
func (o *PostV1FileConfigOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post v1 file config o k response
func (o *PostV1FileConfigOK) Code() int {
	return 200
}

func (o *PostV1FileConfigOK) Error() string {
	return fmt.Sprintf("[POST /v1/file/config][%d] postV1FileConfigOK ", 200)
}

func (o *PostV1FileConfigOK) String() string {
	return fmt.Sprintf("[POST /v1/file/config][%d] postV1FileConfigOK ", 200)
}

func (o *PostV1FileConfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
