// Code generated by go-swagger; DO NOT EDIT.

package file

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostV1FileWafReader is a Reader for the PostV1FileWaf structure.
type PostV1FileWafReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostV1FileWafReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostV1FileWafOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /v1/file/waf] PostV1FileWaf", response, response.Code())
	}
}

// NewPostV1FileWafOK creates a PostV1FileWafOK with default headers values
func NewPostV1FileWafOK() *PostV1FileWafOK {
	return &PostV1FileWafOK{}
}

/*
PostV1FileWafOK describes a response with status code 200, with default header values.

Success. Get a yaml file.
*/
type PostV1FileWafOK struct {
}

// IsSuccess returns true when this post v1 file waf o k response has a 2xx status code
func (o *PostV1FileWafOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post v1 file waf o k response has a 3xx status code
func (o *PostV1FileWafOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post v1 file waf o k response has a 4xx status code
func (o *PostV1FileWafOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post v1 file waf o k response has a 5xx status code
func (o *PostV1FileWafOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post v1 file waf o k response a status code equal to that given
func (o *PostV1FileWafOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post v1 file waf o k response
func (o *PostV1FileWafOK) Code() int {
	return 200
}

func (o *PostV1FileWafOK) Error() string {
	return fmt.Sprintf("[POST /v1/file/waf][%d] postV1FileWafOK ", 200)
}

func (o *PostV1FileWafOK) String() string {
	return fmt.Sprintf("[POST /v1/file/waf][%d] postV1FileWafOK ", 200)
}

func (o *PostV1FileWafOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
