// Code generated by go-swagger; DO NOT EDIT.

package apikey

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/minchao/neuvector-sdk/models"
)

// NewPostV1APIKeyParams creates a new PostV1APIKeyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostV1APIKeyParams() *PostV1APIKeyParams {
	return &PostV1APIKeyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostV1APIKeyParamsWithTimeout creates a new PostV1APIKeyParams object
// with the ability to set a timeout on a request.
func NewPostV1APIKeyParamsWithTimeout(timeout time.Duration) *PostV1APIKeyParams {
	return &PostV1APIKeyParams{
		timeout: timeout,
	}
}

// NewPostV1APIKeyParamsWithContext creates a new PostV1APIKeyParams object
// with the ability to set a context for a request.
func NewPostV1APIKeyParamsWithContext(ctx context.Context) *PostV1APIKeyParams {
	return &PostV1APIKeyParams{
		Context: ctx,
	}
}

// NewPostV1APIKeyParamsWithHTTPClient creates a new PostV1APIKeyParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostV1APIKeyParamsWithHTTPClient(client *http.Client) *PostV1APIKeyParams {
	return &PostV1APIKeyParams{
		HTTPClient: client,
	}
}

/*
PostV1APIKeyParams contains all the parameters to send to the API endpoint

	for the post v1 API key operation.

	Typically these are written to a http.Request.
*/
type PostV1APIKeyParams struct {

	// XAuthToken.
	XAuthToken string

	/* Body.

	   Apikey information
	*/
	Body *models.RESTApikeyCreation

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post v1 API key params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostV1APIKeyParams) WithDefaults() *PostV1APIKeyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post v1 API key params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostV1APIKeyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post v1 API key params
func (o *PostV1APIKeyParams) WithTimeout(timeout time.Duration) *PostV1APIKeyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post v1 API key params
func (o *PostV1APIKeyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post v1 API key params
func (o *PostV1APIKeyParams) WithContext(ctx context.Context) *PostV1APIKeyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post v1 API key params
func (o *PostV1APIKeyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post v1 API key params
func (o *PostV1APIKeyParams) WithHTTPClient(client *http.Client) *PostV1APIKeyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post v1 API key params
func (o *PostV1APIKeyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAuthToken adds the xAuthToken to the post v1 API key params
func (o *PostV1APIKeyParams) WithXAuthToken(xAuthToken string) *PostV1APIKeyParams {
	o.SetXAuthToken(xAuthToken)
	return o
}

// SetXAuthToken adds the xAuthToken to the post v1 API key params
func (o *PostV1APIKeyParams) SetXAuthToken(xAuthToken string) {
	o.XAuthToken = xAuthToken
}

// WithBody adds the body to the post v1 API key params
func (o *PostV1APIKeyParams) WithBody(body *models.RESTApikeyCreation) *PostV1APIKeyParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post v1 API key params
func (o *PostV1APIKeyParams) SetBody(body *models.RESTApikeyCreation) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostV1APIKeyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Auth-Token
	if err := r.SetHeaderParam("X-Auth-Token", o.XAuthToken); err != nil {
		return err
	}
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
