// Code generated by go-swagger; DO NOT EDIT.

package namespace

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetV1DomainParams creates a new GetV1DomainParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetV1DomainParams() *GetV1DomainParams {
	return &GetV1DomainParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1DomainParamsWithTimeout creates a new GetV1DomainParams object
// with the ability to set a timeout on a request.
func NewGetV1DomainParamsWithTimeout(timeout time.Duration) *GetV1DomainParams {
	return &GetV1DomainParams{
		timeout: timeout,
	}
}

// NewGetV1DomainParamsWithContext creates a new GetV1DomainParams object
// with the ability to set a context for a request.
func NewGetV1DomainParamsWithContext(ctx context.Context) *GetV1DomainParams {
	return &GetV1DomainParams{
		Context: ctx,
	}
}

// NewGetV1DomainParamsWithHTTPClient creates a new GetV1DomainParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetV1DomainParamsWithHTTPClient(client *http.Client) *GetV1DomainParams {
	return &GetV1DomainParams{
		HTTPClient: client,
	}
}

/*
GetV1DomainParams contains all the parameters to send to the API endpoint

	for the get v1 domain operation.

	Typically these are written to a http.Request.
*/
type GetV1DomainParams struct {

	// XAuthToken.
	XAuthToken string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get v1 domain params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1DomainParams) WithDefaults() *GetV1DomainParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get v1 domain params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1DomainParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get v1 domain params
func (o *GetV1DomainParams) WithTimeout(timeout time.Duration) *GetV1DomainParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1 domain params
func (o *GetV1DomainParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1 domain params
func (o *GetV1DomainParams) WithContext(ctx context.Context) *GetV1DomainParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1 domain params
func (o *GetV1DomainParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1 domain params
func (o *GetV1DomainParams) WithHTTPClient(client *http.Client) *GetV1DomainParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1 domain params
func (o *GetV1DomainParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAuthToken adds the xAuthToken to the get v1 domain params
func (o *GetV1DomainParams) WithXAuthToken(xAuthToken string) *GetV1DomainParams {
	o.SetXAuthToken(xAuthToken)
	return o
}

// SetXAuthToken adds the xAuthToken to the get v1 domain params
func (o *GetV1DomainParams) SetXAuthToken(xAuthToken string) {
	o.XAuthToken = xAuthToken
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1DomainParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Auth-Token
	if err := r.SetHeaderParam("X-Auth-Token", o.XAuthToken); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
