// Code generated by go-swagger; DO NOT EDIT.

package namespace

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PatchV1DomainNameReader is a Reader for the PatchV1DomainName structure.
type PatchV1DomainNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchV1DomainNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPatchV1DomainNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PATCH /v1/domain/{name}] PatchV1DomainName", response, response.Code())
	}
}

// NewPatchV1DomainNameOK creates a PatchV1DomainNameOK with default headers values
func NewPatchV1DomainNameOK() *PatchV1DomainNameOK {
	return &PatchV1DomainNameOK{}
}

/*
PatchV1DomainNameOK describes a response with status code 200, with default header values.

Success
*/
type PatchV1DomainNameOK struct {
}

// IsSuccess returns true when this patch v1 domain name o k response has a 2xx status code
func (o *PatchV1DomainNameOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this patch v1 domain name o k response has a 3xx status code
func (o *PatchV1DomainNameOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this patch v1 domain name o k response has a 4xx status code
func (o *PatchV1DomainNameOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this patch v1 domain name o k response has a 5xx status code
func (o *PatchV1DomainNameOK) IsServerError() bool {
	return false
}

// IsCode returns true when this patch v1 domain name o k response a status code equal to that given
func (o *PatchV1DomainNameOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the patch v1 domain name o k response
func (o *PatchV1DomainNameOK) Code() int {
	return 200
}

func (o *PatchV1DomainNameOK) Error() string {
	return fmt.Sprintf("[PATCH /v1/domain/{name}][%d] patchV1DomainNameOK ", 200)
}

func (o *PatchV1DomainNameOK) String() string {
	return fmt.Sprintf("[PATCH /v1/domain/{name}][%d] patchV1DomainNameOK ", 200)
}

func (o *PatchV1DomainNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
