// Code generated by go-swagger; DO NOT EDIT.

package scan

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteV1ScanSigstoreRootOfTrustRootNameReader is a Reader for the DeleteV1ScanSigstoreRootOfTrustRootName structure.
type DeleteV1ScanSigstoreRootOfTrustRootNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteV1ScanSigstoreRootOfTrustRootNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteV1ScanSigstoreRootOfTrustRootNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /v1/scan/sigstore/root_of_trust/{root_name}] DeleteV1ScanSigstoreRootOfTrustRootName", response, response.Code())
	}
}

// NewDeleteV1ScanSigstoreRootOfTrustRootNameOK creates a DeleteV1ScanSigstoreRootOfTrustRootNameOK with default headers values
func NewDeleteV1ScanSigstoreRootOfTrustRootNameOK() *DeleteV1ScanSigstoreRootOfTrustRootNameOK {
	return &DeleteV1ScanSigstoreRootOfTrustRootNameOK{}
}

/*
DeleteV1ScanSigstoreRootOfTrustRootNameOK describes a response with status code 200, with default header values.

Success
*/
type DeleteV1ScanSigstoreRootOfTrustRootNameOK struct {
}

// IsSuccess returns true when this delete v1 scan sigstore root of trust root name o k response has a 2xx status code
func (o *DeleteV1ScanSigstoreRootOfTrustRootNameOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete v1 scan sigstore root of trust root name o k response has a 3xx status code
func (o *DeleteV1ScanSigstoreRootOfTrustRootNameOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete v1 scan sigstore root of trust root name o k response has a 4xx status code
func (o *DeleteV1ScanSigstoreRootOfTrustRootNameOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete v1 scan sigstore root of trust root name o k response has a 5xx status code
func (o *DeleteV1ScanSigstoreRootOfTrustRootNameOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete v1 scan sigstore root of trust root name o k response a status code equal to that given
func (o *DeleteV1ScanSigstoreRootOfTrustRootNameOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete v1 scan sigstore root of trust root name o k response
func (o *DeleteV1ScanSigstoreRootOfTrustRootNameOK) Code() int {
	return 200
}

func (o *DeleteV1ScanSigstoreRootOfTrustRootNameOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/scan/sigstore/root_of_trust/{root_name}][%d] deleteV1ScanSigstoreRootOfTrustRootNameOK ", 200)
}

func (o *DeleteV1ScanSigstoreRootOfTrustRootNameOK) String() string {
	return fmt.Sprintf("[DELETE /v1/scan/sigstore/root_of_trust/{root_name}][%d] deleteV1ScanSigstoreRootOfTrustRootNameOK ", 200)
}

func (o *DeleteV1ScanSigstoreRootOfTrustRootNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
