// Code generated by go-swagger; DO NOT EDIT.

package scan

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteV1ScanSigstoreRootOfTrustRootNameVerifierVerifierNameReader is a Reader for the DeleteV1ScanSigstoreRootOfTrustRootNameVerifierVerifierName structure.
type DeleteV1ScanSigstoreRootOfTrustRootNameVerifierVerifierNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteV1ScanSigstoreRootOfTrustRootNameVerifierVerifierNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteV1ScanSigstoreRootOfTrustRootNameVerifierVerifierNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /v1/scan/sigstore/root_of_trust/{root_name}/verifier/{verifier_name}] DeleteV1ScanSigstoreRootOfTrustRootNameVerifierVerifierName", response, response.Code())
	}
}

// NewDeleteV1ScanSigstoreRootOfTrustRootNameVerifierVerifierNameOK creates a DeleteV1ScanSigstoreRootOfTrustRootNameVerifierVerifierNameOK with default headers values
func NewDeleteV1ScanSigstoreRootOfTrustRootNameVerifierVerifierNameOK() *DeleteV1ScanSigstoreRootOfTrustRootNameVerifierVerifierNameOK {
	return &DeleteV1ScanSigstoreRootOfTrustRootNameVerifierVerifierNameOK{}
}

/*
DeleteV1ScanSigstoreRootOfTrustRootNameVerifierVerifierNameOK describes a response with status code 200, with default header values.

Success
*/
type DeleteV1ScanSigstoreRootOfTrustRootNameVerifierVerifierNameOK struct {
}

// IsSuccess returns true when this delete v1 scan sigstore root of trust root name verifier verifier name o k response has a 2xx status code
func (o *DeleteV1ScanSigstoreRootOfTrustRootNameVerifierVerifierNameOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete v1 scan sigstore root of trust root name verifier verifier name o k response has a 3xx status code
func (o *DeleteV1ScanSigstoreRootOfTrustRootNameVerifierVerifierNameOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete v1 scan sigstore root of trust root name verifier verifier name o k response has a 4xx status code
func (o *DeleteV1ScanSigstoreRootOfTrustRootNameVerifierVerifierNameOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete v1 scan sigstore root of trust root name verifier verifier name o k response has a 5xx status code
func (o *DeleteV1ScanSigstoreRootOfTrustRootNameVerifierVerifierNameOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete v1 scan sigstore root of trust root name verifier verifier name o k response a status code equal to that given
func (o *DeleteV1ScanSigstoreRootOfTrustRootNameVerifierVerifierNameOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete v1 scan sigstore root of trust root name verifier verifier name o k response
func (o *DeleteV1ScanSigstoreRootOfTrustRootNameVerifierVerifierNameOK) Code() int {
	return 200
}

func (o *DeleteV1ScanSigstoreRootOfTrustRootNameVerifierVerifierNameOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/scan/sigstore/root_of_trust/{root_name}/verifier/{verifier_name}][%d] deleteV1ScanSigstoreRootOfTrustRootNameVerifierVerifierNameOK ", 200)
}

func (o *DeleteV1ScanSigstoreRootOfTrustRootNameVerifierVerifierNameOK) String() string {
	return fmt.Sprintf("[DELETE /v1/scan/sigstore/root_of_trust/{root_name}/verifier/{verifier_name}][%d] deleteV1ScanSigstoreRootOfTrustRootNameVerifierVerifierNameOK ", 200)
}

func (o *DeleteV1ScanSigstoreRootOfTrustRootNameVerifierVerifierNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
