// Code generated by go-swagger; DO NOT EDIT.

package scan

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/minchao/neuvector-sdk/models"
)

// GetV1ScanStatusReader is a Reader for the GetV1ScanStatus structure.
type GetV1ScanStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetV1ScanStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetV1ScanStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /v1/scan/status] GetV1ScanStatus", response, response.Code())
	}
}

// NewGetV1ScanStatusOK creates a GetV1ScanStatusOK with default headers values
func NewGetV1ScanStatusOK() *GetV1ScanStatusOK {
	return &GetV1ScanStatusOK{}
}

/*
GetV1ScanStatusOK describes a response with status code 200, with default header values.

Success
*/
type GetV1ScanStatusOK struct {
	Payload *models.RESTScanStatusData
}

// IsSuccess returns true when this get v1 scan status o k response has a 2xx status code
func (o *GetV1ScanStatusOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get v1 scan status o k response has a 3xx status code
func (o *GetV1ScanStatusOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 scan status o k response has a 4xx status code
func (o *GetV1ScanStatusOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get v1 scan status o k response has a 5xx status code
func (o *GetV1ScanStatusOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get v1 scan status o k response a status code equal to that given
func (o *GetV1ScanStatusOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get v1 scan status o k response
func (o *GetV1ScanStatusOK) Code() int {
	return 200
}

func (o *GetV1ScanStatusOK) Error() string {
	return fmt.Sprintf("[GET /v1/scan/status][%d] getV1ScanStatusOK  %+v", 200, o.Payload)
}

func (o *GetV1ScanStatusOK) String() string {
	return fmt.Sprintf("[GET /v1/scan/status][%d] getV1ScanStatusOK  %+v", 200, o.Payload)
}

func (o *GetV1ScanStatusOK) GetPayload() *models.RESTScanStatusData {
	return o.Payload
}

func (o *GetV1ScanStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RESTScanStatusData)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
