// Code generated by go-swagger; DO NOT EDIT.

package scan

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetV1ScanRegistryParams creates a new GetV1ScanRegistryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetV1ScanRegistryParams() *GetV1ScanRegistryParams {
	return &GetV1ScanRegistryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1ScanRegistryParamsWithTimeout creates a new GetV1ScanRegistryParams object
// with the ability to set a timeout on a request.
func NewGetV1ScanRegistryParamsWithTimeout(timeout time.Duration) *GetV1ScanRegistryParams {
	return &GetV1ScanRegistryParams{
		timeout: timeout,
	}
}

// NewGetV1ScanRegistryParamsWithContext creates a new GetV1ScanRegistryParams object
// with the ability to set a context for a request.
func NewGetV1ScanRegistryParamsWithContext(ctx context.Context) *GetV1ScanRegistryParams {
	return &GetV1ScanRegistryParams{
		Context: ctx,
	}
}

// NewGetV1ScanRegistryParamsWithHTTPClient creates a new GetV1ScanRegistryParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetV1ScanRegistryParamsWithHTTPClient(client *http.Client) *GetV1ScanRegistryParams {
	return &GetV1ScanRegistryParams{
		HTTPClient: client,
	}
}

/*
GetV1ScanRegistryParams contains all the parameters to send to the API endpoint

	for the get v1 scan registry operation.

	Typically these are written to a http.Request.
*/
type GetV1ScanRegistryParams struct {

	// XAuthToken.
	XAuthToken string

	/* Scope.

	   When set to fed, returned fed registries. When set to local, returned local-defined registries. If there is no query string 'scope', all registries will be returned.
	*/
	Scope *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get v1 scan registry params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1ScanRegistryParams) WithDefaults() *GetV1ScanRegistryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get v1 scan registry params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1ScanRegistryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get v1 scan registry params
func (o *GetV1ScanRegistryParams) WithTimeout(timeout time.Duration) *GetV1ScanRegistryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1 scan registry params
func (o *GetV1ScanRegistryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1 scan registry params
func (o *GetV1ScanRegistryParams) WithContext(ctx context.Context) *GetV1ScanRegistryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1 scan registry params
func (o *GetV1ScanRegistryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1 scan registry params
func (o *GetV1ScanRegistryParams) WithHTTPClient(client *http.Client) *GetV1ScanRegistryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1 scan registry params
func (o *GetV1ScanRegistryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAuthToken adds the xAuthToken to the get v1 scan registry params
func (o *GetV1ScanRegistryParams) WithXAuthToken(xAuthToken string) *GetV1ScanRegistryParams {
	o.SetXAuthToken(xAuthToken)
	return o
}

// SetXAuthToken adds the xAuthToken to the get v1 scan registry params
func (o *GetV1ScanRegistryParams) SetXAuthToken(xAuthToken string) {
	o.XAuthToken = xAuthToken
}

// WithScope adds the scope to the get v1 scan registry params
func (o *GetV1ScanRegistryParams) WithScope(scope *string) *GetV1ScanRegistryParams {
	o.SetScope(scope)
	return o
}

// SetScope adds the scope to the get v1 scan registry params
func (o *GetV1ScanRegistryParams) SetScope(scope *string) {
	o.Scope = scope
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1ScanRegistryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Auth-Token
	if err := r.SetHeaderParam("X-Auth-Token", o.XAuthToken); err != nil {
		return err
	}

	if o.Scope != nil {

		// query param scope
		var qrScope string

		if o.Scope != nil {
			qrScope = *o.Scope
		}
		qScope := qrScope
		if qScope != "" {

			if err := r.SetQueryParam("scope", qScope); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
