// Code generated by go-swagger; DO NOT EDIT.

package scan

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/minchao/neuvector-sdk/models"
)

// GetV1ScanSigstoreRootOfTrustRootNameVerifierVerifierNameReader is a Reader for the GetV1ScanSigstoreRootOfTrustRootNameVerifierVerifierName structure.
type GetV1ScanSigstoreRootOfTrustRootNameVerifierVerifierNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetV1ScanSigstoreRootOfTrustRootNameVerifierVerifierNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetV1ScanSigstoreRootOfTrustRootNameVerifierVerifierNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /v1/scan/sigstore/root_of_trust/{root_name}/verifier/{verifier_name}] GetV1ScanSigstoreRootOfTrustRootNameVerifierVerifierName", response, response.Code())
	}
}

// NewGetV1ScanSigstoreRootOfTrustRootNameVerifierVerifierNameOK creates a GetV1ScanSigstoreRootOfTrustRootNameVerifierVerifierNameOK with default headers values
func NewGetV1ScanSigstoreRootOfTrustRootNameVerifierVerifierNameOK() *GetV1ScanSigstoreRootOfTrustRootNameVerifierVerifierNameOK {
	return &GetV1ScanSigstoreRootOfTrustRootNameVerifierVerifierNameOK{}
}

/*
GetV1ScanSigstoreRootOfTrustRootNameVerifierVerifierNameOK describes a response with status code 200, with default header values.

Success
*/
type GetV1ScanSigstoreRootOfTrustRootNameVerifierVerifierNameOK struct {
	Payload *models.RESTSigstoreVerifier
}

// IsSuccess returns true when this get v1 scan sigstore root of trust root name verifier verifier name o k response has a 2xx status code
func (o *GetV1ScanSigstoreRootOfTrustRootNameVerifierVerifierNameOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get v1 scan sigstore root of trust root name verifier verifier name o k response has a 3xx status code
func (o *GetV1ScanSigstoreRootOfTrustRootNameVerifierVerifierNameOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 scan sigstore root of trust root name verifier verifier name o k response has a 4xx status code
func (o *GetV1ScanSigstoreRootOfTrustRootNameVerifierVerifierNameOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get v1 scan sigstore root of trust root name verifier verifier name o k response has a 5xx status code
func (o *GetV1ScanSigstoreRootOfTrustRootNameVerifierVerifierNameOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get v1 scan sigstore root of trust root name verifier verifier name o k response a status code equal to that given
func (o *GetV1ScanSigstoreRootOfTrustRootNameVerifierVerifierNameOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get v1 scan sigstore root of trust root name verifier verifier name o k response
func (o *GetV1ScanSigstoreRootOfTrustRootNameVerifierVerifierNameOK) Code() int {
	return 200
}

func (o *GetV1ScanSigstoreRootOfTrustRootNameVerifierVerifierNameOK) Error() string {
	return fmt.Sprintf("[GET /v1/scan/sigstore/root_of_trust/{root_name}/verifier/{verifier_name}][%d] getV1ScanSigstoreRootOfTrustRootNameVerifierVerifierNameOK  %+v", 200, o.Payload)
}

func (o *GetV1ScanSigstoreRootOfTrustRootNameVerifierVerifierNameOK) String() string {
	return fmt.Sprintf("[GET /v1/scan/sigstore/root_of_trust/{root_name}/verifier/{verifier_name}][%d] getV1ScanSigstoreRootOfTrustRootNameVerifierVerifierNameOK  %+v", 200, o.Payload)
}

func (o *GetV1ScanSigstoreRootOfTrustRootNameVerifierVerifierNameOK) GetPayload() *models.RESTSigstoreVerifier {
	return o.Payload
}

func (o *GetV1ScanSigstoreRootOfTrustRootNameVerifierVerifierNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RESTSigstoreVerifier)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
