name: Continuous Integration
on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request: { }
  workflow_dispatch: { }
env:
  GOLANG_VERSION: '1.20'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GOLANG_VERSION }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
