// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RESTViolationWorkload r e s t violation workload
//
// swagger:model RESTViolationWorkload
type RESTViolationWorkload struct {

	// count
	// Example: 2
	// Required: true
	Count *int64 `json:"count"`

	// workload
	// Required: true
	Workload *RESTWorkloadBrief `json:"workload"`
}

// Validate validates this r e s t violation workload
func (m *RESTViolationWorkload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateWorkload(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RESTViolationWorkload) validateCount(formats strfmt.Registry) error {

	if err := validate.Required("count", "body", m.Count); err != nil {
		return err
	}

	return nil
}

func (m *RESTViolationWorkload) validateWorkload(formats strfmt.Registry) error {

	if err := validate.Required("workload", "body", m.Workload); err != nil {
		return err
	}

	if m.Workload != nil {
		if err := m.Workload.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("workload")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("workload")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this r e s t violation workload based on the context it is used
func (m *RESTViolationWorkload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateWorkload(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RESTViolationWorkload) contextValidateWorkload(ctx context.Context, formats strfmt.Registry) error {

	if m.Workload != nil {

		if err := m.Workload.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("workload")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("workload")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *RESTViolationWorkload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RESTViolationWorkload) UnmarshalBinary(b []byte) error {
	var res RESTViolationWorkload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
