// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RESTLicenseRequestData r e s t license request data
//
// swagger:model RESTLicenseRequestData
type RESTLicenseRequestData struct {

	// license request
	// Required: true
	LicenseRequest *RESTLicenseRequest `json:"license_request"`
}

// Validate validates this r e s t license request data
func (m *RESTLicenseRequestData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLicenseRequest(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RESTLicenseRequestData) validateLicenseRequest(formats strfmt.Registry) error {

	if err := validate.Required("license_request", "body", m.LicenseRequest); err != nil {
		return err
	}

	if m.LicenseRequest != nil {
		if err := m.LicenseRequest.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("license_request")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("license_request")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this r e s t license request data based on the context it is used
func (m *RESTLicenseRequestData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateLicenseRequest(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RESTLicenseRequestData) contextValidateLicenseRequest(ctx context.Context, formats strfmt.Registry) error {

	if m.LicenseRequest != nil {

		if err := m.LicenseRequest.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("license_request")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("license_request")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *RESTLicenseRequestData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RESTLicenseRequestData) UnmarshalBinary(b []byte) error {
	var res RESTLicenseRequestData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
