// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RESTDomainEntryConfig r e s t domain entry config
//
// swagger:model RESTDomainEntryConfig
type RESTDomainEntryConfig struct {

	// name
	// Example: iperfspace
	// Required: true
	Name *string `json:"name"`

	// tags
	// Example: [""]
	Tags []string `json:"tags"`
}

// Validate validates this r e s t domain entry config
func (m *RESTDomainEntryConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RESTDomainEntryConfig) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this r e s t domain entry config based on context it is used
func (m *RESTDomainEntryConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RESTDomainEntryConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RESTDomainEntryConfig) UnmarshalBinary(b []byte) error {
	var res RESTDomainEntryConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
