// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RESTPwdProfileData r e s t pwd profile data
//
// swagger:model RESTPwdProfileData
type RESTPwdProfileData struct {

	// pwd profile
	// Required: true
	PwdProfile *RESTPwdProfile `json:"pwd_profile"`
}

// Validate validates this r e s t pwd profile data
func (m *RESTPwdProfileData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePwdProfile(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RESTPwdProfileData) validatePwdProfile(formats strfmt.Registry) error {

	if err := validate.Required("pwd_profile", "body", m.PwdProfile); err != nil {
		return err
	}

	if m.PwdProfile != nil {
		if err := m.PwdProfile.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("pwd_profile")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("pwd_profile")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this r e s t pwd profile data based on the context it is used
func (m *RESTPwdProfileData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePwdProfile(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RESTPwdProfileData) contextValidatePwdProfile(ctx context.Context, formats strfmt.Registry) error {

	if m.PwdProfile != nil {

		if err := m.PwdProfile.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("pwd_profile")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("pwd_profile")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *RESTPwdProfileData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RESTPwdProfileData) UnmarshalBinary(b []byte) error {
	var res RESTPwdProfileData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
