// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RESTPwdProfileConfig r e s t pwd profile config
//
// swagger:model RESTPwdProfileConfig
type RESTPwdProfileConfig struct {

	// active
	// Example: true
	Active bool `json:"active,omitempty"`

	// block after failed login count
	// Example: 0
	BlockAfterFailedLoginCount int64 `json:"block_after_failed_login_count,omitempty"`

	// block minutes
	// Example: 0
	BlockMinutes int64 `json:"block_minutes,omitempty"`

	// comment
	Comment string `json:"comment,omitempty"`

	// enable block after failed login
	// Example: false
	EnableBlockAfterFailedLogin bool `json:"enable_block_after_failed_login,omitempty"`

	// enable password expiration
	// Example: false
	EnablePasswordExpiration bool `json:"enable_password_expiration,omitempty"`

	// enable password history
	// Example: true
	EnablePasswordHistory bool `json:"enable_password_history,omitempty"`

	// min digit count
	// Example: 0
	MinDigitCount int64 `json:"min_digit_count,omitempty"`

	// min len
	// Example: 6
	MinLen int64 `json:"min_len,omitempty"`

	// min lowercase count
	// Example: 0
	MinLowercaseCount int64 `json:"min_lowercase_count,omitempty"`

	// min special count
	// Example: 0
	MinSpecialCount int64 `json:"min_special_count,omitempty"`

	// min uppercase count
	// Example: 0
	MinUppercaseCount int64 `json:"min_uppercase_count,omitempty"`

	// name
	// Example: default
	// Required: true
	Name *string `json:"name"`

	// password expire after days
	// Example: 0
	PasswordExpireAfterDays int64 `json:"password_expire_after_days,omitempty"`

	// password keep history count
	// Example: 0
	PasswordKeepHistoryCount int64 `json:"password_keep_history_count,omitempty"`

	// session timeout
	// Example: 300
	SessionTimeout int64 `json:"session_timeout,omitempty"`
}

// Validate validates this r e s t pwd profile config
func (m *RESTPwdProfileConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RESTPwdProfileConfig) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this r e s t pwd profile config based on context it is used
func (m *RESTPwdProfileConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RESTPwdProfileConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RESTPwdProfileConfig) UnmarshalBinary(b []byte) error {
	var res RESTPwdProfileConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
