// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RESTThreatsData r e s t threats data
//
// swagger:model RESTThreatsData
type RESTThreatsData struct {

	// threats
	// Required: true
	Threats []*Threat `json:"threats"`
}

// Validate validates this r e s t threats data
func (m *RESTThreatsData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateThreats(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RESTThreatsData) validateThreats(formats strfmt.Registry) error {

	if err := validate.Required("threats", "body", m.Threats); err != nil {
		return err
	}

	for i := 0; i < len(m.Threats); i++ {
		if swag.IsZero(m.Threats[i]) { // not required
			continue
		}

		if m.Threats[i] != nil {
			if err := m.Threats[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("threats" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("threats" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this r e s t threats data based on the context it is used
func (m *RESTThreatsData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateThreats(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RESTThreatsData) contextValidateThreats(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Threats); i++ {

		if m.Threats[i] != nil {

			if swag.IsZero(m.Threats[i]) { // not required
				return nil
			}

			if err := m.Threats[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("threats" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("threats" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *RESTThreatsData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RESTThreatsData) UnmarshalBinary(b []byte) error {
	var res RESTThreatsData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
