// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RESTApikey r e s t apikey
//
// swagger:model RESTApikey
type RESTApikey struct {

	// apikey name
	// Example: token-cicd-scan
	// Required: true
	ApikeyName *string `json:"apikey_name"`

	// apikey secret
	// Example: 0u+tVOWNPRfpCK7p9qz
	ApikeySecret string `json:"apikey_secret,omitempty"`

	// created by entity
	// Example: admin
	CreatedByEntity string `json:"created_by_entity,omitempty"`

	// created timestamp
	// Example: 11515020888
	CreatedTimestamp int64 `json:"created_timestamp,omitempty"`

	// description
	// Example: cicd image scanning
	Description string `json:"description,omitempty"`

	// expiration hours
	// Example: 1
	ExpirationHours uint32 `json:"expiration_hours,omitempty"`

	// expiration timestamp
	// Example: 11515020888
	ExpirationTimestamp int64 `json:"expiration_timestamp,omitempty"`

	// expiration type
	// Example: never
	// Required: true
	ExpirationType *string `json:"expiration_type"`

	// role
	// Example: admin
	// Required: true
	Role *string `json:"role"`

	// role domains
	RoleDomains *RESTApikeyRoleDomains `json:"role_domains,omitempty"`
}

// Validate validates this r e s t apikey
func (m *RESTApikey) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateApikeyName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateExpirationType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRole(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRoleDomains(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RESTApikey) validateApikeyName(formats strfmt.Registry) error {

	if err := validate.Required("apikey_name", "body", m.ApikeyName); err != nil {
		return err
	}

	return nil
}

func (m *RESTApikey) validateExpirationType(formats strfmt.Registry) error {

	if err := validate.Required("expiration_type", "body", m.ExpirationType); err != nil {
		return err
	}

	return nil
}

func (m *RESTApikey) validateRole(formats strfmt.Registry) error {

	if err := validate.Required("role", "body", m.Role); err != nil {
		return err
	}

	return nil
}

func (m *RESTApikey) validateRoleDomains(formats strfmt.Registry) error {
	if swag.IsZero(m.RoleDomains) { // not required
		return nil
	}

	if m.RoleDomains != nil {
		if err := m.RoleDomains.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("role_domains")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("role_domains")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this r e s t apikey based on the context it is used
func (m *RESTApikey) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateRoleDomains(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RESTApikey) contextValidateRoleDomains(ctx context.Context, formats strfmt.Registry) error {

	if m.RoleDomains != nil {

		if swag.IsZero(m.RoleDomains) { // not required
			return nil
		}

		if err := m.RoleDomains.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("role_domains")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("role_domains")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *RESTApikey) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RESTApikey) UnmarshalBinary(b []byte) error {
	var res RESTApikey
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// RESTApikeyRoleDomains r e s t apikey role domains
//
// swagger:model RESTApikeyRoleDomains
type RESTApikeyRoleDomains struct {

	// domains
	// Example: ["domain1","domain2"]
	Domains []string `json:"domains"`

	// role
	// Example: admin
	Role string `json:"role,omitempty"`
}

// Validate validates this r e s t apikey role domains
func (m *RESTApikeyRoleDomains) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this r e s t apikey role domains based on context it is used
func (m *RESTApikeyRoleDomains) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RESTApikeyRoleDomains) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RESTApikeyRoleDomains) UnmarshalBinary(b []byte) error {
	var res RESTApikeyRoleDomains
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
