// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RESTServiceConfig r e s t service config
//
// swagger:model RESTServiceConfig
type RESTServiceConfig struct {

	// baseline profile
	BaselineProfile string `json:"baseline_profile,omitempty"`

	// comment
	// Required: true
	Comment *string `json:"comment"`

	// domain
	// Required: true
	Domain *string `json:"domain"`

	// name
	// Required: true
	Name *string `json:"name"`

	// not scored
	// Example: true
	NotScored bool `json:"not_scored,omitempty"`

	// policy mode
	PolicyMode string `json:"policy_mode,omitempty"`
}

// Validate validates this r e s t service config
func (m *RESTServiceConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateComment(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDomain(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RESTServiceConfig) validateComment(formats strfmt.Registry) error {

	if err := validate.Required("comment", "body", m.Comment); err != nil {
		return err
	}

	return nil
}

func (m *RESTServiceConfig) validateDomain(formats strfmt.Registry) error {

	if err := validate.Required("domain", "body", m.Domain); err != nil {
		return err
	}

	return nil
}

func (m *RESTServiceConfig) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this r e s t service config based on context it is used
func (m *RESTServiceConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RESTServiceConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RESTServiceConfig) UnmarshalBinary(b []byte) error {
	var res RESTServiceConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
