// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RESTDlpGroupData r e s t dlp group data
//
// swagger:model RESTDlpGroupData
type RESTDlpGroupData struct {

	// dlp group
	// Required: true
	DlpGroup *RESTDlpGroup `json:"dlp_group"`
}

// Validate validates this r e s t dlp group data
func (m *RESTDlpGroupData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDlpGroup(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RESTDlpGroupData) validateDlpGroup(formats strfmt.Registry) error {

	if err := validate.Required("dlp_group", "body", m.DlpGroup); err != nil {
		return err
	}

	if m.DlpGroup != nil {
		if err := m.DlpGroup.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("dlp_group")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("dlp_group")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this r e s t dlp group data based on the context it is used
func (m *RESTDlpGroupData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDlpGroup(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RESTDlpGroupData) contextValidateDlpGroup(ctx context.Context, formats strfmt.Registry) error {

	if m.DlpGroup != nil {

		if err := m.DlpGroup.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("dlp_group")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("dlp_group")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *RESTDlpGroupData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RESTDlpGroupData) UnmarshalBinary(b []byte) error {
	var res RESTDlpGroupData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
