// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RESTSniffersData r e s t sniffers data
//
// swagger:model RESTSniffersData
type RESTSniffersData struct {

	// sniffers
	// Required: true
	Sniffers []*RESTSnifferInfo `json:"sniffers"`
}

// Validate validates this r e s t sniffers data
func (m *RESTSniffersData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSniffers(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RESTSniffersData) validateSniffers(formats strfmt.Registry) error {

	if err := validate.Required("sniffers", "body", m.Sniffers); err != nil {
		return err
	}

	for i := 0; i < len(m.Sniffers); i++ {
		if swag.IsZero(m.Sniffers[i]) { // not required
			continue
		}

		if m.Sniffers[i] != nil {
			if err := m.Sniffers[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("sniffers" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("sniffers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this r e s t sniffers data based on the context it is used
func (m *RESTSniffersData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSniffers(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RESTSniffersData) contextValidateSniffers(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Sniffers); i++ {

		if m.Sniffers[i] != nil {

			if swag.IsZero(m.Sniffers[i]) { // not required
				return nil
			}

			if err := m.Sniffers[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("sniffers" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("sniffers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *RESTSniffersData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RESTSniffersData) UnmarshalBinary(b []byte) error {
	var res RESTSniffersData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
