// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RESTControllerConfig r e s t controller config
//
// swagger:model RESTControllerConfig
type RESTControllerConfig struct {

	// debug
	// Example: ["log","parser","tcp","session","error"]
	Debug []string `json:"debug"`
}

// Validate validates this r e s t controller config
func (m *RESTControllerConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this r e s t controller config based on context it is used
func (m *RESTControllerConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RESTControllerConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RESTControllerConfig) UnmarshalBinary(b []byte) error {
	var res RESTControllerConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
