// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RESTApikeyData r e s t apikey data
//
// swagger:model RESTApikeyData
type RESTApikeyData struct {

	// apikey
	// Required: true
	Apikey *RESTApikey `json:"apikey"`
}

// Validate validates this r e s t apikey data
func (m *RESTApikeyData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateApikey(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RESTApikeyData) validateApikey(formats strfmt.Registry) error {

	if err := validate.Required("apikey", "body", m.Apikey); err != nil {
		return err
	}

	if m.Apikey != nil {
		if err := m.Apikey.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("apikey")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("apikey")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this r e s t apikey data based on the context it is used
func (m *RESTApikeyData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateApikey(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RESTApikeyData) contextValidateApikey(ctx context.Context, formats strfmt.Registry) error {

	if m.Apikey != nil {

		if err := m.Apikey.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("apikey")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("apikey")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *RESTApikeyData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RESTApikeyData) UnmarshalBinary(b []byte) error {
	var res RESTApikeyData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
