// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RESTController r e s t controller
//
// swagger:model RESTController
type RESTController struct {

	// cluster ip
	// Example: 10.1.5.1
	// Required: true
	ClusterIP *string `json:"cluster_ip"`

	// connection state
	// Example: connected
	// Required: true
	ConnectionState *string `json:"connection_state"`

	// cpus
	// Required: true
	Cpus *string `json:"cpus"`

	// created at
	// Example: 2018-01-24T17:16:59Z
	// Required: true
	// Format: date-time
	CreatedAt *strfmt.DateTime `json:"created_at"`

	// disconnected at
	// Required: true
	DisconnectedAt *string `json:"disconnected_at"`

	// display name
	// Example: allinone
	// Required: true
	DisplayName *string `json:"display_name"`

	// domain
	// Required: true
	Domain *string `json:"domain"`

	// host id
	// Example: 2AU7:TIEN:O5KX:QK56:LFQP:IJSV:FXBN:QJV7
	// Required: true
	HostID *string `json:"host_id"`

	// host name
	// Example: ubuntu64
	// Required: true
	HostName *string `json:"host_name"`

	// id
	// Example: b63882364cd1a56b2234ce0c9266ca403090e5e8148
	// Required: true
	ID *string `json:"id"`

	// joined at
	// Example: 2018-01-24T17:17:10Z
	// Required: true
	// Format: date-time
	JoinedAt *strfmt.DateTime `json:"joined_at"`

	// map key is string type
	// Example: {"com.docker.compose.config-hash":"e94ce458b3bc97cd478e9738a759d76fb819"}
	// Required: true
	Labels map[string]string `json:"labels"`

	// leader
	// Example: true
	// Required: true
	Leader *bool `json:"leader"`

	// memory limit
	// Example: 0
	// Required: true
	MemoryLimit *int64 `json:"memory_limit"`

	// name
	// Example: allinone
	// Required: true
	Name *string `json:"name"`

	// orch conn last error
	// Required: true
	OrchConnLastError *string `json:"orch_conn_last_error"`

	// orch conn status
	// Required: true
	OrchConnStatus *string `json:"orch_conn_status"`

	// started at
	// Example: 2018-01-24T17:16:59Z
	// Required: true
	// Format: date-time
	StartedAt *strfmt.DateTime `json:"started_at"`

	// version
	// Example: 0.1.0
	// Required: true
	Version *string `json:"version"`
}

// Validate validates this r e s t controller
func (m *RESTController) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateClusterIP(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateConnectionState(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCpus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDisconnectedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDisplayName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDomain(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateHostID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateHostName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateJoinedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLabels(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLeader(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMemoryLimit(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOrchConnLastError(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOrchConnStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStartedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVersion(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RESTController) validateClusterIP(formats strfmt.Registry) error {

	if err := validate.Required("cluster_ip", "body", m.ClusterIP); err != nil {
		return err
	}

	return nil
}

func (m *RESTController) validateConnectionState(formats strfmt.Registry) error {

	if err := validate.Required("connection_state", "body", m.ConnectionState); err != nil {
		return err
	}

	return nil
}

func (m *RESTController) validateCpus(formats strfmt.Registry) error {

	if err := validate.Required("cpus", "body", m.Cpus); err != nil {
		return err
	}

	return nil
}

func (m *RESTController) validateCreatedAt(formats strfmt.Registry) error {

	if err := validate.Required("created_at", "body", m.CreatedAt); err != nil {
		return err
	}

	if err := validate.FormatOf("created_at", "body", "date-time", m.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *RESTController) validateDisconnectedAt(formats strfmt.Registry) error {

	if err := validate.Required("disconnected_at", "body", m.DisconnectedAt); err != nil {
		return err
	}

	return nil
}

func (m *RESTController) validateDisplayName(formats strfmt.Registry) error {

	if err := validate.Required("display_name", "body", m.DisplayName); err != nil {
		return err
	}

	return nil
}

func (m *RESTController) validateDomain(formats strfmt.Registry) error {

	if err := validate.Required("domain", "body", m.Domain); err != nil {
		return err
	}

	return nil
}

func (m *RESTController) validateHostID(formats strfmt.Registry) error {

	if err := validate.Required("host_id", "body", m.HostID); err != nil {
		return err
	}

	return nil
}

func (m *RESTController) validateHostName(formats strfmt.Registry) error {

	if err := validate.Required("host_name", "body", m.HostName); err != nil {
		return err
	}

	return nil
}

func (m *RESTController) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *RESTController) validateJoinedAt(formats strfmt.Registry) error {

	if err := validate.Required("joined_at", "body", m.JoinedAt); err != nil {
		return err
	}

	if err := validate.FormatOf("joined_at", "body", "date-time", m.JoinedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *RESTController) validateLabels(formats strfmt.Registry) error {

	if err := validate.Required("labels", "body", m.Labels); err != nil {
		return err
	}

	return nil
}

func (m *RESTController) validateLeader(formats strfmt.Registry) error {

	if err := validate.Required("leader", "body", m.Leader); err != nil {
		return err
	}

	return nil
}

func (m *RESTController) validateMemoryLimit(formats strfmt.Registry) error {

	if err := validate.Required("memory_limit", "body", m.MemoryLimit); err != nil {
		return err
	}

	return nil
}

func (m *RESTController) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *RESTController) validateOrchConnLastError(formats strfmt.Registry) error {

	if err := validate.Required("orch_conn_last_error", "body", m.OrchConnLastError); err != nil {
		return err
	}

	return nil
}

func (m *RESTController) validateOrchConnStatus(formats strfmt.Registry) error {

	if err := validate.Required("orch_conn_status", "body", m.OrchConnStatus); err != nil {
		return err
	}

	return nil
}

func (m *RESTController) validateStartedAt(formats strfmt.Registry) error {

	if err := validate.Required("started_at", "body", m.StartedAt); err != nil {
		return err
	}

	if err := validate.FormatOf("started_at", "body", "date-time", m.StartedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *RESTController) validateVersion(formats strfmt.Registry) error {

	if err := validate.Required("version", "body", m.Version); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this r e s t controller based on context it is used
func (m *RESTController) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RESTController) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RESTController) UnmarshalBinary(b []byte) error {
	var res RESTController
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
