// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RESTScanAwsFuncDetail r e s t scan aws func detail
//
// swagger:model RESTScanAwsFuncDetail
type RESTScanAwsFuncDetail struct {

	// scan brief
	// Required: true
	ScanBrief *RESTScanBrief `json:"scan_brief"`

	// scan report
	// Required: true
	ScanReport *RESTScanReport `json:"scan_report"`
}

// Validate validates this r e s t scan aws func detail
func (m *RESTScanAwsFuncDetail) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateScanBrief(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateScanReport(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RESTScanAwsFuncDetail) validateScanBrief(formats strfmt.Registry) error {

	if err := validate.Required("scan_brief", "body", m.ScanBrief); err != nil {
		return err
	}

	if m.ScanBrief != nil {
		if err := m.ScanBrief.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("scan_brief")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("scan_brief")
			}
			return err
		}
	}

	return nil
}

func (m *RESTScanAwsFuncDetail) validateScanReport(formats strfmt.Registry) error {

	if err := validate.Required("scan_report", "body", m.ScanReport); err != nil {
		return err
	}

	if m.ScanReport != nil {
		if err := m.ScanReport.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("scan_report")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("scan_report")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this r e s t scan aws func detail based on the context it is used
func (m *RESTScanAwsFuncDetail) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateScanBrief(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateScanReport(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RESTScanAwsFuncDetail) contextValidateScanBrief(ctx context.Context, formats strfmt.Registry) error {

	if m.ScanBrief != nil {

		if err := m.ScanBrief.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("scan_brief")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("scan_brief")
			}
			return err
		}
	}

	return nil
}

func (m *RESTScanAwsFuncDetail) contextValidateScanReport(ctx context.Context, formats strfmt.Registry) error {

	if m.ScanReport != nil {

		if err := m.ScanReport.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("scan_report")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("scan_report")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *RESTScanAwsFuncDetail) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RESTScanAwsFuncDetail) UnmarshalBinary(b []byte) error {
	var res RESTScanAwsFuncDetail
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
