// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RESTSysNetConfigConfig r e s t sys net config config
//
// swagger:model RESTSysNetConfigConfig
type RESTSysNetConfigConfig struct {

	// detect unmanaged wl
	// Example: true
	DetectUnmanagedWl bool `json:"detect_unmanaged_wl,omitempty"`

	// disable net policy
	// Example: false
	DisableNetPolicy bool `json:"disable_net_policy,omitempty"`

	// net service policy mode
	NetServicePolicyMode string `json:"net_service_policy_mode,omitempty"`

	// net service status
	// Example: true
	NetServiceStatus bool `json:"net_service_status,omitempty"`
}

// Validate validates this r e s t sys net config config
func (m *RESTSysNetConfigConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this r e s t sys net config config based on context it is used
func (m *RESTSysNetConfigConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RESTSysNetConfigConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RESTSysNetConfigConfig) UnmarshalBinary(b []byte) error {
	var res RESTSysNetConfigConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
